composer.json, src/module-elasticsuite-catalog-autocomplete/Block/Search/Form/Autocomplete.php, src/module-elasticsuite-catalog-autocomplete/Model/Autocomplete/Product/DataProvider.php, src/module-elasticsuite-catalog-autocomplete/Model/Autocomplete/Terms/DataProvider.php, src/module-elasticsuite-catalog-autocomplete/composer.json, src/module-elasticsuite-catalog-autocomplete/etc/frontend/di.xml, src/module-elasticsuite-catalog-autocomplete/etc/module.xml, src/module-elasticsuite-catalog-autocomplete/registration.php, src/module-elasticsuite-catalog-autocomplete/view/frontend/layout/default.xml, src/module-elasticsuite-catalog-autocomplete/view/frontend/requirejs-config.js, src/module-elasticsuite-catalog-autocomplete/view/frontend/templates/form.mini.phtml, src/module-elasticsuite-catalog-autocomplete/view/frontend/web/css/source/_module.less, src/module-elasticsuite-catalog-autocomplete/view/frontend/web/js/form-mini.js, src/module-elasticsuite-catalog-autocomplete/view/frontend/web/template/autocomplete/category.html, src/module-elasticsuite-catalog-autocomplete/view/frontend/web/template/autocomplete/product.html, src/module-elasticsuite-catalog-autocomplete/view/frontend/web/template/autocomplete/term.html, src/module-elasticsuite-catalog/Model/ResourceModel/Product/Fulltext/Collection.php, src/module-elasticsuite-core/Search/Adapter/ElasticSuite/Request/Mapper.php, src/module-elasticsuite-core/Search/Request/Builder.php, src/module-elasticsuite-core/Search/Request/Query/Builder.php, src/module-elasticsuite-core/Search/Request/Query/Fulltext/QueryBuilder.php, src/module-elasticsuite-thesaurus/Plugin/QueryRewrite.php
Products, Categories and search terms renderers included.
- Autocomplete results are still based on the previous POC version, with a little improvement.
=> Append a generic autocomplete display framework.

src/module-elasticsuite-core/Index/Indices/Config/Reader.php
[#61] fix merge datasource to an existing index
=> Add datasource name attribute as identifier node config in the reader

src/module-elasticsuite-catalog/Model/Layer/Filter/Attribute.php
Fixes #68, the core issue is using a custom source model on an attribute however this fix would be sufficient in preventing the front-end from not working a result.
=> fix: Options could be empty, validation added

src/module-elasticsuite-catalog/Model/Product/Indexer/Fulltext/Datasource/AttributeData.php
When configurable attribute is not used in LayeredNav, L155 fails indexation due to attribute is not in array.
E.g. you have clothing with color and size, where color is always some complex naming "crimson/blood red/peach" and color_group for this is "red". Color is not used in layered while color_group is. Such solution results in Notice: Undefined offset: <colorAttributeId> which is fixable by isset proposed here.
=> Conf product may have conf. attribute not used in layered nav

src/module-elasticsuite-core/etc/di.xml
This is a proposal for fixing the issue where a fatal error is thrown on catalogsearch result page on Magento 2.1 EE with `module-advanced-search` is enabled.
This bug affects the "standard" search result page.
I think this is better to fix it on our side by just declaring a dummy (the default one which does nothing) data provider for search suggestions, instead of asking people to simply shut down the Advanced Search module.
=> It's easier for people to not being forced to disable EE module when using our engine. 
=> This way, people can continue to use Advanced Search features like Recommendations (even if it is a perf killer, they have the choice to use it if they want).
=> We will be able to switch to our custom implementation later without having to say to people "ok now you can …
=> Make elasticsuite use the dummy data provider for search suggestions

src/module-elasticsuite-catalog/Model/ResourceModel/Product/Indexer/Fulltext/Action/Full.php
Performance related. This query is processed so many times that an explicit casting here should be worth it.
=> Explicit casting to int when building visibility filter.

composer.json
This is due to the previous merging of #212 which does not work with prior versions of the Elasticsearch PHP Client.
=> Set requirements for Elasticsearch client to 2.2.3

src/module-elasticsuite-core/Block/Adminhtml/Search/Request/RelevanceConfig/Form.php, src/module-elasticsuite-core/Model/Search/Request/RelevanceConfig.php, src/module-elasticsuite-core/Model/Search/Request/RelevanceConfig/ReaderPool.php, src/module-elasticsuite-core/Search/Request/RelevanceConfig/App/Config.php, src/module-elasticsuite-core/etc/di.xml
This PR is intended to fix the backward incompatible changes made by Magento between 2.1.2 and 2.1.3 versions.
This is essentially occuring on objects inheriting or using the Magento\Framework\App\Config class (Reader, Scope pools, etc ...).
Some (slights) parts of Relevance Configuration have been refactored to be 2.1.3 compliant.
This piece of code has also been tested against a Magento 2.1.2 version and is working, which should prevent us from having to release several versions of the module in the future.
Let me know,
Best regards,
=> Feature refactoring relevance configuration (2.1.3 compatibility)

src/module-elasticsuite-core/Index/Mapping/Field.php
This one fix #257.
@romainruaud : can you test all combination of attribute config is now valid.
* Searchable only
* Sortable only
* Filterable + Sortable 
* ....
=> Fix mapping of sortable only fields.

src/module-elasticsuite-core/Model/ResourceModel/Search/Request/RelevanceConfig.php
Will fix the latent issue described on #288 
Low impact since the bug can occurs only when calling explicitely the ```saveConfig``` or ```deleteConfig``` method, which is not the case when editing the configuration in the Back-Office.
This could only happen on specific code written to use this functions.
=> Implements the saveConfig method to use correct "scope_code" field.

src/module-elasticsuite-catalog/Block/Plugin/Adminhtml/Product/Attribute/Edit/Tab/FrontPlugin.php, src/module-elasticsuite-catalog/Helper/Attribute.php, src/module-elasticsuite-catalog/Model/Eav/Indexer/Fulltext/Datasource/AbstractAttributeData.php, src/module-elasticsuite-catalog/Setup/UpgradeSchema.php, src/module-elasticsuite-catalog/etc/module.xml, src/module-elasticsuite-core/Api/Index/Mapping/FieldInterface.php, src/module-elasticsuite-core/Index/Mapping.php, src/module-elasticsuite-core/Index/Mapping/Field.php, src/module-elasticsuite-core/Test/Unit/Index/Mapping/FieldTest.php
Proposal for removing this unused field.
Maybe we should not, since this was exposed publicly by the Field interface, I let you choose.
=> Remove the "is_used_in_autocomplete" field.

src/module-elasticsuite-catalog/Block/Plugin/Adminhtml/Product/Attribute/Edit/Tab/FrontPlugin.php, src/module-elasticsuite-catalog/view/adminhtml/templates/catalog/product/attribute/js.phtml, src/module-elasticsuite-swatches/view/adminhtml/templates/catalog/product/attribute/js.phtml
Ensure booleans can be set as filterable / filterable in search
Also ensure to hide the "is_displayed_in_autocomplete" for attributes which are not "filterable in search" => since they are used as a facet on the search result page, they need to be filterable in search.
=> Better attribute configuration screen

src/module-elasticsuite-virtual-category/Model/Preview.php, src/module-elasticsuite-virtual-category/Model/Rule.php
- Reduce the recursion level for standard categories.
- Merge children categories into an unique should clause when possible
=> Virtual category optimization

src/module-elasticsuite-virtual-category/Block/Adminhtml/Catalog/Category/Tab/Product.php, src/module-elasticsuite-virtual-category/etc/adminhtml/di.xml, src/module-elasticsuite-virtual-category/view/adminhtml/requirejs-config.js, src/module-elasticsuite-virtual-category/view/adminhtml/web/js/component/catalog/category/form/assign-products.js
Removing the column was easy, except since the block name is hardcoded by Magento, I had to rewrite it.
But magento does not handle adding products to a category if the "position" field does not exists on the grid. I had to override also the Javascript component to manage this case.
=> Remove position column

src/module-elasticsuite-catalog/etc/di.xml
Will prevent cases like #340 by disallowing attributes creation with attribute_code identical to elasticsuite custom fields such "stock" or "category"
=> Adding elasticsuite internal nested attributes as reserved.

src/module-elasticsuite-catalog/Model/Category/Indexer/Fulltext.php
This is a fix for #384 
I just removed the $data parameter which was not used and therefore useless.
=> Remove not used data parameter for category fulltext indexing.

src/module-elasticsuite-catalog/Model/Eav/Indexer/Fulltext/Datasource/AbstractAttributeData.php
They were not indexed previously, which was preventing our fellow users to create custom "prices" attributes and setting them as filterable in front office.
This has been discussed on #341 : this issue occurs in fact not for special_price only, but for any attribute having a price backend.
Regards
=> Allow to index prices attributes.

.travis.yml, composer.json, src/module-elasticsuite-catalog-optimizer/Model/OptimizerRepository.php, src/module-elasticsuite-thesaurus/Model/ThesaurusRepository.php
This PR embeds the Magento's marketplace EQP check (https://github.com/magento/marketplace-eqp) to the build.
It also contains two fixes to perform the build without error with a severity level of 10 (the minimum level to be published on the marketplace).
We could consider fixing all the other warnings shown for lower severity level later. Let me know.
=> Adding Magento's EQP to build

src/module-elasticsuite-swatches/Helper/Swatches.php, src/module-elasticsuite-swatches/Model/Plugin/ProductImage.php, src/module-elasticsuite-swatches/Model/Plugin/ProductSubstitute.php, src/module-elasticsuite-swatches/etc/di.xml
This will fix bugs for Magento 2.1.6 where swatches have ben refactored (our old plugin is not called anymore).
This refactoring have been tested against 2.1.5 and 2.1.6 and is working with full backward compatibility.
It also fixes #393 on both versions.
=> Fix swatches for Magento 2.1.6

src/module-elasticsuite-catalog/etc/di.xml
This one fixes #392 
When using previously ```Magento\CatalogSearch\Model\Layer\Search\ItemCollectionProvider``` we were using a ```Magento\CatalogSearch\Model\ResourceModel\Fulltext\SearchCollectionFactory``` which was using a ```Magento\CatalogSearch\Model\ResourceModel\Fulltext\SearchCollection```.
This one always had the searchRequestName set to "quick_search_container", even when browsing the catalog.
I replaced it by direct usage of ElasticSuite Fulltext collection, allowing us to have the default value for catalog navigation which is ```catalog_view_container```
=> Ensure catalog requests have the proper type.

src/module-elasticsuite-catalog/Setup/InstallData.php, src/module-elasticsuite-virtual-category/Setup/InstallData.php
This one is easy to reproduce on a completely fresh install : project sources but with an empty database.
- have a module which is creating categories.
Even if you add a dependency on Smile_ElasticsuiteCatalog or Smile_ElasticsuiteVirtualCategory, you will face the following error : 
```
Attribute with attributeCode "use_name_in_product_search" does not exist. 
```
**Even if the attribute was properly created before** by elasticsuite setups.
This is due to the fact that when using ```addAttribute```, Magento does not clear the EAV Cache properly. Therefore it does not find the attribute later when creating categories.
This one should be considered as **blocking to deploy project from scratch** on newly created environments (such as MECE or other PaaS platforms).
Regards
=> Ensure proper EAV Attributes cache cleaning after creating attributes.

src/module-elasticsuite-catalog/Model/Autocomplete/Product/Attribute/DataProvider.php, src/module-elasticsuite-catalog/Model/Autocomplete/Product/Collection/Filter.php, src/module-elasticsuite-catalog/etc/frontend/di.xml
Your refactoring was causing a fatal error because of using a non existent variable.
=> Fixing autocomplete refactoring.

src/module-elasticsuite-catalog-rule/Model/Rule/Condition/Product/QueryBuilder.php
is One of rules are of input type string, but should still use a TERMS query.
=> Fixed issue with "is one of" rules not working.

src/module-elasticsuite-catalog/Model/ResourceModel/Product/Indexer/Fulltext/Datasource/CategoryData.php
This one is a workaround for this issue : https://github.com/magento/magento2/issues/10421
This could lead to several errors, since we rely on this table when reindexing products, and provoke failures when trying to index category names into products.
To reproduce : 
- Have the indexers in "Update on Save" mode.
- Delete the category YYY where the product XXX is affected.
- Try to execute an action which triggers a reindex of this product (save it in the BO, or event **order it in front-office**)
- The action will fail, due to "Undefined index: YYY on module-elasticsuite-catalog/Model/ResourceModel/Product/Indexer/Fulltext/Datasource/CategoryData
.php on line 93"
This is due to the fact we rely on a table where old rows concerning a deleted category are still present.
Regards,
=> Prevent undefined offset error on deleted categories.

src/module-elasticsuite-core/view/frontend/web/js/form-mini.js
Previous version (the #489) is bugged, it is throwing JS error. I did not notice it probably because I had a cached version with hardcoded value of 250 for testing which did not get expired properly.
It does not seem to be possible to access this.options.debounceTimer when launching the _.debounce function as far as I saw. Imho it's not a killer feature to allow a such configuration. For now we can go with arbitrary defined value.
Please merge this one to ensure the bug is fixed.
=> Remove configurable delay for autocomplete debounce.

src/module-elasticsuite-core/Search/Adapter/Elasticsuite/Spellchecker.php
Potential fix for #412 
Two points here : 
- The detection of spelling type (exact or fuzzy) was based on the "spelling" analyzer. It cannot work for fields which are not used for spellcheck.
=> For this one, I have a question, why using "spelling" analyzer for term vectors ? Changing it for both 'search' and 'spelling' gives me better results for fields which are not used for spellchecking.
- The term vector query did not use "dfs" : this implies it is ran to a random shard. By doing this way, a query can be exact one time (matches document in the randomized shard) but fuzzy next time (not matching document in the new randomized shard).
=> About this one, I can understand this may be due to performances issues when using 'dfs'. Let me know where the cursor should be put between exact …
=> Fix term vector usage to use also default search field.

src/module-elasticsuite-virtual-category/Plugin/Catalog/Category/ReindexOnChange.php, src/module-elasticsuite-virtual-category/etc/di.xml
This is a fix for #465 
Enforce reindexing (if set to Update on Save) when switching a category from normal mode to virtual mode.
Nothing done for mview, since this is actually working properly (due to the SQL trigger).
=> Enforce reindexing when category is set to virtual.

src/module-elasticsuite-core/Helper/IndexSettings.php
While Magento allows upper case characters in store codes, elasticsearch does not allow upper case characters in index names. Therefore we have to transform the store code before using it as part of the index name.
larasearch had the same problem which was fixed in [issue 43](https://github.com/iverberk/larasearch/issues/43).
=> Handle store codes with upper case characters

src/module-elasticsuite-thesaurus/Model/Index.php
=> Fix synonyms handling when query does not contains any words.

src/module-elasticsuite-virtual-category/Setup/InstallData.php
This piece of code was already moved to the dedicated VirtualCategorySetup class during the setup refactoring, it should be removed from the InstallData, especially since $this->eavConfig is not defined anymore.
=> Fix not existing object into VirtualCategories Install.

src/module-elasticsuite-catalog/etc/elasticsuite_indices.xml
You were right @afoucret (I know, you will say "as usual"), just putting the sku as "isUsedInSpellcheck" allow to obtain exact matching on it (as we discussed about the term vector query using only spellchecked field) .
Tested working OK with : 
- mix of letters and number : 101177BLG
- full letters : HEWPUTRABC
- full numbers : 11610018
- mixed with dash : ABC-V1P80
- overly complicated sku : HEW-V1P80UTR#ABA
So this should gladly fix #412 and fix #524 with a less intrusive implementation than #548
=> Adding SKU to spellchecked field to allow exact matching on it.

src/module-elasticsuite-catalog-rule/Api/Rule/Condition/Product/SpecialAttributeInterface.php, src/module-elasticsuite-catalog-rule/Model/Rule/Condition/Product.php, src/module-elasticsuite-catalog-rule/Model/Rule/Condition/Product/QueryBuilder.php, src/module-elasticsuite-catalog-rule/Model/Rule/Condition/Product/SpecialAttribute/HasImage.php, src/module-elasticsuite-catalog-rule/Model/Rule/Condition/Product/SpecialAttribute/IsDiscount.php, src/module-elasticsuite-catalog-rule/Model/Rule/Condition/Product/SpecialAttribute/IsInStock.php, src/module-elasticsuite-catalog-rule/Model/Rule/Condition/Product/SpecialAttributesProvider.php, src/module-elasticsuite-catalog-rule/etc/di.xml, src/module-elasticsuite-virtual-category/Model/Rule/Condition/Product.php
Moving all hardcoded reference to "special attributes" (is_in_stock, price.is_discount, has_image) to a SpecialAttributeProvider extendable via the DI.
Here is also a proposal to implement a special attribute "is_new" injectable via DI : 
di.xml : 
```
<type name="Smile\ElasticsuiteCatalogRule\Model\Rule\Condition\Product\SpecialAttributesProvider">
<arguments>
<argument name="attributes" xsi:type="array">
<item name="is_product_new" xsi:type="object">Smile\ElasticsuiteCatalogRule\Model\Rule\Condition\Product\SpecialAttribute\IsNew</item>
</argument>
</arguments>
</type>
```
"IsNew" class : 
```
<?php
/**
* DISCLAIMER
* Do not edit or add to this file if you wish to upgrade Smile Elastic Suite to newer
* versions in the future.
*
* @category  Smile
* @package …
```
=> Refactoring "special attributes" to allow extending them easily.

src/module-elasticsuite-catalog/view/frontend/web/js/attribute-filter.js
There was a bad character (probably because you are coding with a mac) in this javascript file.
This is causing a JS error when bundling is enabled.
=> Remove irregular whitespace.

src/module-elasticsuite-catalog/Block/Navigation.php
Proposal of fix for #593 
```$this->getLayer()->getCurrentCategory()->getDisplayMode() === \Magento\Catalog\Model\Category::DM_PAGE``` is not enough because this can cause the filters to disappear on search if the root category is configured with Content Mode.
I did not found something better to test if we are on catalog than testing if current layer is an instance of ```\Magento\Catalog\Model\Layer\Category```. This could cause some bugs when people override this class without inheriting it... but should we manage such a mistake ?
=> Do not display navigation block on content mode categories.

src/module-elasticsuite-catalog/Model/Product/Indexer/Fulltext/Action/Full.php
This is a fix for #610 and has been tested OK on customer environment.
@afoucret I think once we are done merging this one, I'll publish minor 2.4.1
=> Process parent product when reindexing with a list of product ids

src/module-elasticsuite-catalog/Block/Navigation.php, src/module-elasticsuite-catalog/Model/Layer/FilterList.php, src/module-elasticsuite-catalog/Model/Product/Attribute/CoverageRateProvider.php, src/module-elasticsuite-catalog/Model/Product/Indexer/Fulltext/Datasource/AttributeData.php, src/module-elasticsuite-catalog/Model/Product/Indexer/Fulltext/Datasource/PriceData.php, src/module-elasticsuite-catalog/Model/ResourceModel/Product/Fulltext/Collection.php, src/module-elasticsuite-catalog/etc/elasticsuite_indices.xml
As we discussed together, I refactored the product collection coverage.
This time, no additional PHP classes, I simply put it at the same place of the "countByAttributeSetId".
I decided to let the count by attribute set id in place, and flag it as deprecated (since it was a public method). I just added a new bucket into the loadProductCount method, to be used when calculating coverage rate in the Navigation block.
This will also fix #645 btw
=> Refactoring product collection coverage.

src/module-elasticsuite-core/etc/elasticsuite_indices.xsd
Datasources may be declared after mapping in document type definition.
=> Fix invalid document order node

src/module-elasticsuite-thesaurus/Block/Adminhtml/Thesaurus/Edit/Form.php, src/module-elasticsuite-thesaurus/Controller/Adminhtml/Thesaurus/Save.php, src/module-elasticsuite-thesaurus/Model/ResourceModel/Thesaurus.php, src/module-elasticsuite-thesaurus/Model/Thesaurus.php
To be merged in 2.4.x and cascaded to master.
Fix #674 
Note : We should consider a big refactoring of the way thesaurus are saved for next version, and move it to the EntityManager instead of deprecated save/load methods.
=> Cleanup thesaurus store ids management.

src/module-elasticsuite-catalog/Helper/AbstractAttribute.php, src/module-elasticsuite-catalog/Test/Unit/Helper/AbstractAttributeTest.php, src/module-elasticsuite-core/Api/Index/Mapping/FieldInterface.php, src/module-elasticsuite-core/Test/Unit/Index/Mapping/FieldTest.php
Improvement related to #673
Now using long instead of integer for attribute created from the admin.
=> Fix integer indexing for very long values.

src/module-elasticsuite-catalog/Model/ResourceModel/Product/Indexer/Fulltext/Action/Full.php
There may be inconsistency issues when retrieving relations by child when using Magento Commerce (EE).
This is due to the fact that on Magento EE, `catalog_product_relation` is built like this : 
```
CREATE TABLE `catalog_product_relation` (
`parent_id` int(10) unsigned NOT NULL COMMENT 'Parent ID',
`child_id` int(10) unsigned NOT NULL COMMENT 'Child ID',
PRIMARY KEY (`parent_id`,`child_id`),
KEY `CATALOG_PRODUCT_RELATION_CHILD_ID` (`child_id`),
CONSTRAINT `CAT_PRD_RELATION_CHILD_ID_SEQUENCE_PRD_SEQUENCE_VAL` FOREIGN KEY (`child_id`) REFERENCES `sequence_product` (`sequence_value`) ON DELETE CASCADE,
CONSTRAINT `CAT_PRD_RELATION_PARENT_ID_CAT_PRD_ENTT_ENTT_ID` FOREIGN KEY (`parent_id`) REFERENCES `catalog_product_entity` (`row_id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 …
```
=> Ensure proper retrieval of parent entity_id 

src/module-elasticsuite-catalog/Model/Autocomplete/Product/AttributeConfig.php, src/module-elasticsuite-catalog/Model/Autocomplete/Product/ItemFactory.php
This one fix #682 
Main problem is due to the fact that "special_price" is not selected in autocomplete. I thought `addPriceData()` would do this, but it's not the case.
The only reason the same bug is not appearing on catalog listing is that special_price is set to `used_in_product_listing=1` and get automatically loaded by the layer.
I did not want to load all attributes `used_in_product_listing=1` in the autocomplete (for performances concern, however, this would have fixed the issue easily), so I added only 'special_price' to the list of default selected attributes.
I intentionally omitted to add "special_from_date" and "special_to_date".
This is due to the fact that they are used only with Magento CE and this could cause errors when these attributes are missing (if they were deleted, …
=> Fix autocomplete special price

src/module-elasticsuite-catalog/etc/adminhtml/routes.xml
Actual version of routes.xml leads to a 404 error when accessing the "Merchandiser" link.
=> Fixing wrong route for merchandiser in admin.

src/module-elasticsuite-catalog/Model/Layer/Filter/Attribute.php
Issue: https://github.com/Smile-SA/elasticsuite/issues/729
This one fix the missing adminSortIndex issue.
If you change the option label in the filter attribute in the admin panel, the script doesn't see this option, doesn't set key adminSortIndex and throws an error in usort() function.
This issue exists in all versions.
Regards,
Grzegorz
=> Check if adminSoertIndex key exists

src/module-elasticsuite-tracker/Block/Config.php, src/module-elasticsuite-tracker/view/frontend/layout/default.xml, src/module-elasticsuite-tracker/view/frontend/requirejs-config.js, src/module-elasticsuite-tracker/view/frontend/templates/config.phtml, src/module-elasticsuite-tracker/view/frontend/web/js/tracking.js, src/module-elasticsuite-tracker/view/frontend/web/js/user-consent.js
I added a Javascript class to handle user consent.
Default implementation is based on cookie restriction (`true` if cookie restriction is disabled, `true` if restriction is enabled and the user accepted cookies, `false` otherwise).
There are 2 points of extension : 
- via the layout, one can change the UserConsent JS component used by the block.
- via the requirejs-config, one change the mapping of the default component name to point on a custom implementation.
I tested overriding with a dummy one (returning always true or false) and it was working.
=> Feature gdpr consent tracking

src/module-elasticsuite-catalog/Setup/CatalogSetup.php, src/module-elasticsuite-catalog/Setup/UpgradeData.php, src/module-elasticsuite-catalog/etc/module.xml
=> Use is_used_in_promo_rules instead of is_searchable for the image attribute.

src/module-elasticsuite-catalog/Block/Plugin/Adminhtml/Product/Attribute/Edit/Tab/FrontPlugin.php, src/module-elasticsuite-core/Index/Mapping/Field.php, src/module-elasticsuite-core/Test/Unit/Index/Mapping/FieldTest.php
Fix #827 
I discovered there was also a bug in the BO attribute edit block, this PR embeds the fix (dependency block was broken).
I changed the isUsedInSpellecheck method for FieldInterface and added the associated unit test.
Let me know
=> Fix prevent spellcheck fields

src/module-elasticsuite-core/Model/Search.php
This one is a pre-requisite for fixing #855 
This is just changing the implemented interface from `\Magento\Framework\Api\Search\SearchInterface` to `\Magento\Search\Api\SearchInterface`.
The `\Magento\Search\Api\SearchInterface` is an `@api` flagged one also, and is empty and just inheriting the `\Magento\Framework\Api\Search\SearchInterface` : https://github.com/magento/magento2/blob/2.2-develop/app/code/Magento/Search/Api/SearchInterface.php
So for me, this is not too much risky to inherit this interface instead of the previous one, since they are the same for now. Also, the new interface is part of the `Magento_Search` module but we already depend on it.
Regards
=> Change the implemented interface of the Elasticsuite Search Engine.

src/module-elasticsuite-virtual-category/Model/Rule.php
I have an issue that I can't exactly reproduce on a test environment... All I know, is once some setup has been done with virtual categories, I have a null pointer error on search results, coming from this snippet.
I've fixed this with the most logic code (and it works) for me, but I can't tell if something else should be done.
Feel free to send me feedback.
=> Avoid null pointer exception when storeId is not defined

src/module-elasticsuite-catalog-rule/Block/Product/Conditions.php, src/module-elasticsuite-catalog-rule/Controller/Adminhtml/Product/Rule/Conditions.php, src/module-elasticsuite-virtual-category/Block/Adminhtml/Catalog/Category/Checkboxes/Tree.php, src/module-elasticsuite-virtual-category/Block/Adminhtml/Catalog/Category/VirtualRule.php, src/module-elasticsuite-virtual-category/Model/Rule.php, src/module-elasticsuite-virtual-category/Model/Rule/Condition/Product.php, src/module-elasticsuite-virtual-category/Plugin/Catalog/Category/ChooserPlugin.php, src/module-elasticsuite-virtual-category/etc/adminhtml/di.xml
This one was more painful to do than I expected because it's kinda hard to inject the context (current category) and to keep it along all ajax requests used by the rule form (even this form has different behavior when adding a new condition or when editing a previously created one).
Actually this prevent you from creating a "Category" condition outside of the current category tree.
It also prevent the user to create a "Category" condition on the same category.
Imho another PR (or new commit on this one ?) will be needed to prevent the same thing for the "Category Root".
Let me know,
=> Prevent building cross-tree virtual categories.

src/module-elasticsuite-catalog/etc/module.xml
Fix #886.
@romainruaud : can you test it please.
=> Add dependency to Magento_LayeredNavigationStaging for Smile_ElasticsuiteCatalog. 

src/module-elasticsuite-catalog-optimizer/Ui/Component/Listing/Column/YesNo.php, src/module-elasticsuite-catalog-optimizer/view/adminhtml/ui_component/smile_elasticsuite_catalog_optimizer_form.xml, src/module-elasticsuite-catalog-optimizer/view/adminhtml/web/js/components/form/optimizer/fieldset-visibility.js, src/module-elasticsuite-catalog/Ui/Component/Search/Term/Listing/DataProvider.php, src/module-elasticsuite-catalog/view/adminhtml/ui_component/search_term_listing.xml
Just a proposal of UX for the conditional behavior of the optimizers.
Actually, I decided to keep the "Request Type" selector. It will show/hide an additional fieldset according to which request type you choose : 
-  Category Product View fieldset
--- Apply to : "all categories" / "selected categories"
--- A category picker is shown if "selected categories" is chosen
- Catalog Product Search fieldset
--- Apply to "all search requests" / "selected requests"
--- A dynamic grid can be opened and filled if "selected requests" is chosen
That's where I am now. I'm thinking on switch the "selected" pattern to an exclusion, or maybe to allow both inclusion and exclusion, I'm not sure what is the more user friendly.
Btw, this UX is a bit complex (dynamicRows linked to a grid opening in a slide …
=> Adding conditional fieldsets for optimizers.

src/module-elasticsuite-catalog-optimizer/Model/Optimizer/ApplierList.php, src/module-elasticsuite-catalog-optimizer/Model/Optimizer/OptimizerList.php, src/module-elasticsuite-catalog-optimizer/Model/ResourceModel/Optimizer/Limitation.php
Finally I decided to rework what I initially had.
For now, the preview support in the BO is still missing, but I wanted to have your thoughts on the chosen implementation first : 
- previous caching of all optimizers rules remains intact
- I add an object which is able to filter optimizers if not applicable in current context.
- the cost is just an additional SQL query on runtime (no effect on category pages thanks to caching).
maybe the whole correlation map between optimizers and query_id/category_id could be loaded and cached only once to prevent this SQL query.
Let me know
=> Conditional appliance of optimizers.

src/module-elasticsuite-catalog/Model/ResourceModel/Product/Indexer/Fulltext/Action/Full.php, src/module-elasticsuite-catalog/Model/ResourceModel/Product/Indexer/Fulltext/Datasource/CategoryData.php
=> Add proper exception handling when retrieving TableMaintainer class.

src/module-elasticsuite-catalog/Model/Eav/Indexer/Fulltext/Datasource/AbstractAttributeData.php
Some sites may have attributes with custom backend models. We should allow them to be indexed provided they extend one of the backend models we support.
=> Allow Subclasses of backend models to be indexed

src/module-elasticsuite-catalog/Model/Layer/Filter/Attribute.php
=> Proper compute of admin sort when option values contains single quotes.

src/module-elasticsuite-core/Model/Search/RequestBuilder.php
Fix #1010 
Tested working OK with two store views : `fr` and `default`.
I have 5 products named "sac" on the french store, which are named "bag" on the default website.
Tested OK via cURL (note the store code used in URL) : 
Search for "sac" on default store view, get 0 results : 
```
curl -X GET "http://magento22ce.lxc/rest/V1/search?searchCriteria\[requestName\]=quick_search_container&searchCriteria\[filterGroups\]\[0\]\[filters\]\[0\]\[field\]=search_term&searchCriteria\[filterGroups\]\[0\]\[filters\]\[0\]\[value\]=sac" 
{"items":[],"aggregations":{"buckets":[],"bucket_names":[]},"search_criteria":{"request_name":"quick_search_container","filter_groups":[{"filters":[{"field":"search_term","value":"sac","condition_type":"eq"}]}]},"total_count":0}
```
Same query on french store : 
``` …
```
=> Replace StoreResolver by StoreManager into request builder.

src/module-elasticsuite-swatches/Block/Plugin/Adminhtml/Product/Attribute/Edit/Tab/FrontPlugin.php, src/module-elasticsuite-swatches/Plugin/Layer/Filter/SwatchAttribute.php
Fix #1059 where `Magento\Swatches\Model\SwatchAttributeType` is not existing in Magento <2.4
Maybe we could merge it to 2.5x and cascade.
=> Replace SwatchAttributeType by Swatch Helper to ensure BC.

src/module-elasticsuite-core/Model/Search/Request/RelevanceConfig.php
=> Fix relevance config save.

src/module-elasticsuite-catalog/view/frontend/web/template/autocomplete/product.html
Replace #1139 to be merged in 2.6.x instead of master.
=> Remove regular price span to show price label

src/module-elasticsuite-core/Api/Search/Request/Container/FilterInterface.php
Basically an extension due to the discussion in #1158. Since one does not need to return a \Smile\ElasticsuiteCore\Search\Request\QueryInterface the doc block comment should indicate that.
=> Extend the doc block to explain the possibility to return null to unset filter

src/module-elasticsuite-catalog-optimizer/Controller/Adminhtml/Optimizer/Save.php, src/module-elasticsuite-catalog-optimizer/Model/Optimizer.php, src/module-elasticsuite-catalog-optimizer/Model/Optimizer/Limitation/Identities.php, src/module-elasticsuite-catalog/Block/CatalogSearch/Result/Cache.php, src/module-elasticsuite-catalog/Controller/Adminhtml/Term/Merchandiser/Save.php, src/module-elasticsuite-catalog/Model/Product/Search/Position.php, src/module-elasticsuite-catalog/Plugin/CatalogSearch/Indexer/FulltextPlugin.php, src/module-elasticsuite-catalog/etc/di.xml, src/module-elasticsuite-catalog/view/frontend/layout/catalogsearch_result_index.xml, src/module-elasticsuite-virtual-category/Plugin/CatalogSearch/Indexer/FulltextPlugin.php, src/module-elasticsuite-virtual-category/etc/di.xml
- Add a cache tag to Magento popular search results and allow cleaning it after full reindex.
- Purge all virtual categories parent categories tree after full reindex.
I can amend this PR if it's not enough, let me know
=> Fix cache policy

src/module-elasticsuite-catalog/Block/Plugin/Adminhtml/Product/Attribute/Edit/Tab/FrontPlugin.php, src/module-elasticsuite-catalog/Helper/AbstractAttribute.php, src/module-elasticsuite-catalog/Setup/CatalogSetup.php, src/module-elasticsuite-catalog/Setup/InstallSchema.php, src/module-elasticsuite-catalog/Setup/UpgradeSchema.php, src/module-elasticsuite-catalog/etc/module.xml, src/module-elasticsuite-catalog/i18n/en_US.csv, src/module-elasticsuite-catalog/i18n/fr_FR.csv, src/module-elasticsuite-core/Api/Index/Mapping/FieldInterface.php, src/module-elasticsuite-core/Index/Mapping/Field.php, src/module-elasticsuite-core/Search/Adapter/Elasticsuite/Request/SortOrder/Builder.php, src/module-elasticsuite-core/Search/Request/SortOrder/Nested.php, src/module-elasticsuite-core/Search/Request/SortOrder/SortOrderBuilder.php, src/module-elasticsuite-core/Search/Request/SortOrder/Standard.php, src/module-elasticsuite-core/Search/Request/SortOrderInterface.php, src/module-elasticsuite-core/Test/Unit/Index/Mapping/FieldTest.php
This one allow to fix for each attribute (and both sorting direction) how we are supposed to set the "missing" parameter of the ES sort order.
Default values are equal to what was done previously (DESC => _last, ASC => _first) so it will be transparent after upgrade.
Will fix #560 and #362 by letting our fellow users to define how they want the sort order to behave.
=> Feature missing sort

src/module-elasticsuite-catalog/Model/Product/Indexer/Fulltext/Datasource/InventoryData.php, src/module-elasticsuite-catalog/Model/ResourceModel/Product/Indexer/Fulltext/Datasource/InventoryData.php, src/module-elasticsuite-catalog/Model/ResourceModel/Product/Indexer/Fulltext/Datasource/InventoryDataInterface.php, src/module-elasticsuite-catalog/etc/di.xml
Created an additional module with a somewhat evocative name, but I'm not so sure about it anymore, since \Magento\CatalogInventory\Api\StockRegistryInterface and \Magento\CatalogInventory\Api\StockConfigurationInterface are cleared marked as deprecated (see full list in https://devdocs.magento.com/guides/v2.3/inventory/catalog-inventory-replacements.html).
Having the changes directly in elasticsuite-catalog would remove the need for the extra interface I had to introduce.
=> Feature #1196 Multi Source Inventory support

src/module-elasticsuite-catalog/Plugin/Rss/CategoryPlugin.php, src/module-elasticsuite-catalog/etc/frontend/di.xml
=> Fixes #1213 Fulltext collection for category RSS

src/module-elasticsuite-catalog/Model/ResourceModel/Product/Indexer/Fulltext/Datasource/InventoryData.php
Fixes Smile-SA/elasticsuite#1223
On a side note; is there a specific reason for joining on SKU? The index table (`inventory_stock_x`) does contain a `product_id` column, no need to join `catalog_product_entity`. Create a secondary pull request with the adjusted select statement https://github.com/Smile-SA/elasticsuite/pull/1225.
=> Fixes Smile-SA/elasticsuite#1223

src/module-elasticsuite-catalog/Plugin/Search/RequestMapperPlugin.php, src/module-elasticsuite-core/etc/di.xml
For now, these 2 fixes allows to run Venia PWA in front of a Magento 2.3 with Elasticsuite.
Only catalog search is supported for now, since Venia uses legacy "Product" endpoint for category navigation.
=> Fix graphql compatibility

src/module-elasticsuite-catalog/Model/Layer/Filter/Attribute.php
=> Apply current filter label to state with escaping.

src/module-elasticsuite-tracker/view/frontend/layout/default.xml
Good afternoon,
Just one typo error with the script declaration "_Smile_ElasticsuiteTracker::js/tracking.js_" (anyway, it include correctly this javascript file).
And some inconsistents with the declaration of head.additional which is a block not a container 
(Same problem on Magento_GoogleAnalytics, this is not solved in my version of _Magento 2.3_ - https://github.com/magento/magento2/issues/16497)
Personally, I would rather move the script tracking.js into _before.body.end_ before _smile.tracker.page.base_ block.
I think you recommends to place it in the <head>, so if someone aborts a load of the page, the script might get executed.
"It helps you to accurately record traffic stats because your header scripts are loaded earlier than any other scripts on your page."
Cheers,
Ilan …
=> head.additional declaration

src/module-elasticsuite-core/Search/Adapter/Elasticsuite/Request/Aggregation/Builder.php, src/module-elasticsuite-core/Search/Adapter/Elasticsuite/Request/Aggregation/BuilderInterface.php, src/module-elasticsuite-core/Search/Adapter/Elasticsuite/Request/Aggregation/PipelineBuilder/BucketSelector.php, src/module-elasticsuite-core/Search/Adapter/Elasticsuite/Request/Aggregation/PipelineBuilderInterface.php, src/module-elasticsuite-core/Search/Request/Aggregation/AggregationBuilder.php, src/module-elasticsuite-core/Search/Request/Aggregation/Bucket/AbstractBucket.php, src/module-elasticsuite-core/Search/Request/Aggregation/Bucket/DateHistogram.php, src/module-elasticsuite-core/Search/Request/Aggregation/Bucket/Histogram.php, src/module-elasticsuite-core/Search/Request/Aggregation/Bucket/QueryGroup.php, src/module-elasticsuite-core/Search/Request/Aggregation/Bucket/SignificantTerm.php, src/module-elasticsuite-core/Search/Request/Aggregation/Bucket/Term.php, src/module-elasticsuite-core/Search/Request/Aggregation/Pipeline/AbstractPipeline.php, src/module-elasticsuite-core/Search/Request/Aggregation/Pipeline/BucketSelector.php, src/module-elasticsuite-core/Search/Request/Aggregation/PipelineFactory.php, src/module-elasticsuite-core/Search/Request/BucketInterface.php, src/module-elasticsuite-core/Search/Request/ContainerConfiguration/BaseConfig.php, src/module-elasticsuite-core/Search/Request/ContainerConfiguration/BaseConfig/Converter.php, src/module-elasticsuite-core/Search/Request/PipelineInterface.php, src/module-elasticsuite-core/Test/Unit/Search/Adapter/Elasticsuite/Request/Aggregation/Builder/TermTest.php, src/module-elasticsuite-core/Test/Unit/Search/Adapter/Elasticsuite/Request/Aggregation/BuilderTest.php, src/module-elasticsuite-core/Test/Unit/Search/Request/Aggregation/AggregationBuilderTest.php, src/module-elasticsuite-core/Test/Unit/Search/Request/Aggregation/AggregationFactoryTest.php, src/module-elasticsuite-core/Test/Unit/Search/Request/Aggregation/PipelineFactoryTest.php, src/module-elasticsuite-core/etc/di.xml, src/module-elasticsuite-core/etc/elasticsuite_search_request.xsd
Both can be defined in a container.
Only bucket selector pipeline aggregation for now.
=> Aggregations: support for pipeline aggs and filter

src/module-elasticsuite-tracker/view/frontend/web/js/tracking.js
Add an alt tag to the tracking pixel so that it is treated as a decorative element in WCAG scanners.
=> Add an alt attribute to the tracking image.

src/module-elasticsuite-tracker/view/frontend/templates/config.phtml, src/module-elasticsuite-tracker/view/frontend/templates/variables/page.phtml
by browser plugin (ex: ublock origin)
=> Fixes #1321 Prevent js errors if tracker blocked (2.6.x)

src/module-elasticsuite-catalog/Model/ResourceModel/Product/Indexer/Fulltext/Datasource/PriceData.php
2.6.x / M2 2.2.x version of PR #1339 
As support for price index dimensions/segmentation was introduced in 2.2.6 and 2.3.0, the object manager is used to keep compatibility with M2 versions < 2.2.6
=> Fixes #1322 support price index segmentation 2.6.x

src/module-elasticsuite-catalog/Model/Product/Indexer/Fulltext/Datasource/InventoryData.php, src/module-elasticsuite-catalog/Model/ResourceModel/Product/Indexer/Fulltext/Datasource/Deprecation/InventoryData.php
Fix for #1243 
Introduce a Deprecation model that allow continue working with legacy CatalogInventory tables in case of MSI is disabled.
=> Allow Inventory Data indexer to work without MSI

src/module-elasticsuite-virtual-category/Model/ResourceModel/Product/Indexer/Fulltext/Datasource/CategoryData.php
Tested working on my multi store environment. Behavior of "use_store_positions" is still working.
Tested by returning directly "null" with `getUseStorePositionsAttribute`, indexation is not broken. Of course in this case, results are a bit messy because you can have several products on position 1 (a product is 1 on global settings, another is 1 for a specific store). But this would imply having product positions already set into the table without the attribute existing, which should rarely occurs.
=> Rationalize the join, and apply it only if the attribute is existing.

src/module-elasticsuite-catalog-optimizer/Model/Optimizer/Preview.php, src/module-elasticsuite-catalog-optimizer/Test/Unit/Model/Optimizer/PreviewTest.php
fix for https://github.com/Smile-SA/elasticsuite/issues/1418
=> add check empty array in optimizer preview and code optimization

src/module-elasticsuite-catalog-optimizer/Ui/Component/Optimizer/Form/Modifier/SearchTerms.php
The fix obviously looks like a fix, there might be in the future a need of a rework or refactoring of 
- \Smile\ElasticsuiteCatalogOptimizer\Model\Optimizer\Limitation\ReadHandler
- \Smile\ElasticsuiteCatalogOptimizer\Ui\Component\Optimizer\Form\Modifier\Limitation
- \Smile\ElasticsuiteCatalogOptimizer\Ui\Component\Optimizer\Form\Modifier\SearchTerms
which have redundant and interdependent code.
=> Fixes #1494 JS error Optimizer empty terms selection

src/module-elasticsuite-core/Search/Request/ContainerConfiguration/BaseConfig/Reader.php
to avoid the last loaded module declaring some having the final say
=> Allow requests xml config aggs providers merge

src/module-elasticsuite-core/Search/Adapter/Elasticsuite/Request/Aggregation/Builder.php, src/module-elasticsuite-core/Search/Request/Aggregation/Metric.php, src/module-elasticsuite-core/Search/Request/MetricInterface.php
not available through the XML declaration though.
A case could be made that 
- "config" could be named "parameters", but "field" is already a parameter in itself
- not all metrics aggs do actually use a "field" parameter (see currently unsupported [weight avg aggregation](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-weight-avg-aggregation.html))
Maybe a broader rework of metrics aggs is necessary in the long run.
=> Supporting extra parameters/config for metrics

src/module-elasticsuite-virtual-category/etc/di.xml, src/module-elasticsuite-virtual-category/etc/webapi_rest/di.xml
closes #1513
As discussed, this PR registers the `VirtualCategoryLocator` only in the `webapi_rest` context.
This prevents the GraphQL framework to try to create a field with an undefined `SmileElasticsuiteVirtualCategoryDataVirtualRuleInterface` type.
I left the `<preference for="Smile\ElasticsuiteVirtualCategory\Api\Data\VirtualRuleInterface" type="Smile\ElasticsuiteVirtualCategory\Model\Rule"/>` in the global `di.xml`.
If you think this would benefit from a test, I'd appreciate guidance to know where you'd prefer to add it.
=> fix: prevent internal error in GraphQL queries

src/module-elasticsuite-catalog/view/adminhtml/web/js/form/element/product-sorter.js
so there is no need for recreating observers/subscriptions.
This is useful for any third-party UI component using editPositions as an import/listen.
=> Fixing the way edit/sort positions are resetted

src/module-elasticsuite-virtual-category/Model/ResourceModel/Product/Indexer/Fulltext/Changelog/Writer.php
We use `table_prefix' => 'prefix_`. When we updating a virtual category in adminhtml (e.g change product position), there will be an exception (only in logs):
~~~
Could not schedule products for reindexing : SQLSTATE[42S02]: Base table or view not found: 1146 Table 'magento.catalogsearch_fulltext_cl'
~~~
This pull request add table_prefix to `$changelogTableName`
=> Fix exception on full index generation, if magento uses table prefix

src/module-elasticsuite-catalog-optimizer/Model/Optimizer/Limitation/Identities.php, src/module-elasticsuite-catalog-optimizer/Model/Optimizer/Limitation/ReadHandler.php
from grid with FPC active.
Minor cosmetic changes on the read handler.
=> Fixes #1583 deleting optimizer w/query limitation

src/module-elasticsuite-catalog/Plugin/Ui/Category/Form/DataProviderPlugin.php
to avoid a pageSize of getSize() set in the collection ie all matching products.
Problematic on a virtual category without any rule set yet: the whole catalog matches.
Quite costly if the catalog is even of a medium size (~ 50K products).
=> Fixes #1581 Explicit fulltext collection page size

src/module-elasticsuite-catalog/Model/Product/Indexer/Fulltext/Datasource/InventoryData.php
Update InventoryData.php to work with both return types: deprecated and inventorydatainterface...
=> Update InventoryData.php to work with both return types

src/module-elasticsuite-catalog/Controller/Navigation/Filter/Ajax.php, src/module-elasticsuite-catalog/Model/ResourceModel/Product/Fulltext/Collection.php, src/module-elasticsuite-catalog/Plugin/Ui/Category/Form/DataProviderPlugin.php
when only fetching aggregations.
Keeps the "Show all" working by distinguishing between NO page size set ("Show all") and a page size of 0.
Also covers someone setting a page size of null for the fun.
=> Fixes #1591 #1581 Explicit collection page size

src/module-elasticsuite-catalog/view/adminhtml/web/js/category/filter-config/dynamic-rows.js
which mirrors the way the collection of attributes is sorted when attributes have the same default_position (ie. attribute defined position).
Record id is only valid for initially UNpinned attributes.
=> Fixes #1617 Use attribute id as last resort order

src/module-elasticsuite-catalog-optimizer/view/adminhtml/ui_component/smile_elasticsuite_catalog_optimizer_form.xml
for attribute based search optimizers
=> Fixes #1635 log1p instead of log for logarithmic fn (2.2.x)

src/module-elasticsuite-catalog/view/frontend/web/js/range-slider-widget.js
Note that the side effect on the histogram values already worked beforehand.
It's just that values were not rounded.
=> Fix application of Math.round on slider histogram values

src/module-elasticsuite-virtual-category/Model/Rule.php
when it is the category/store tree root category.
Will now behave similarly in merchandiser preview/frontend (with a store id context) and in admin with the "All store views" context.
=> Fixes #1629 Better ignoring of virtual root category

src/module-elasticsuite-catalog/Plugin/Search/RequestMapperPlugin.php, src/module-elasticsuite-core/Model/Search/RequestBuilder.php
when no sort order is provided and using the quick_search_container/in a search context.
=> Fixes #1660 Search terms positions sorting on REST and GraphQL

src/module-elasticsuite-catalog-optimizer/Model/ResourceModel/Optimizer/Config/Attributes/Collection.php, src/module-elasticsuite-catalog-optimizer/etc/di.xml, src/module-elasticsuite-catalog-optimizer/view/adminhtml/ui_component/smile_elasticsuite_catalog_optimizer_form.xml
useable for "Based on attribute value" optimizers, nested fields not being supported at the moment.
=> Fixes #1619 Remove "price" from the avail. attributes

src/module-elasticsuite-swatches/Block/Navigation/Renderer/Swatches/RenderLayered.php
Related PR: #1503 
I noticed that PR #1503 broke the manual sorting of the swatches. My solution would be to just fall back to the core method `getSwatchData()` if the attribute is set to manual sorting. The core method works just fine in this case.
- Create a text swatch attribute, set sorting to 'manual'
- Version used 2.8.4 + Magento 2.3.4
=> Fix swatches manual sorting

src/module-elasticsuite-tracker/Model/Event/DotObject.php, src/module-elasticsuite-tracker/Model/Event/Mapping/Enforcer.php, src/module-elasticsuite-tracker/Model/Event/Mapping/TypeEnforcer/AbstractTypeEnforcer.php, src/module-elasticsuite-tracker/Model/Event/Mapping/TypeEnforcer/Boolean.php, src/module-elasticsuite-tracker/Model/Event/Mapping/TypeEnforcer/Double.php, src/module-elasticsuite-tracker/Model/Event/Mapping/TypeEnforcer/Integer.php, src/module-elasticsuite-tracker/Model/Event/Mapping/TypeEnforcerCollector.php, src/module-elasticsuite-tracker/Model/Event/Mapping/TypeEnforcerInterface.php, src/module-elasticsuite-tracker/Model/EventIndex.php, src/module-elasticsuite-tracker/etc/di.xml
when indexing events for boolean, integer and double properties.
Reduces the risk of document being rejected if Elasticsearch cannot coerce a field value into its intended type.
=> Fixes #1702 Explicit cast of tracker properties

src/module-elasticsuite-tracker/Model/ResourceModel/EventQueue.php
usefull if DB storage table was populated with external data.
=> Preventing indexing cron failure on bad json data

src/module-elasticsuite-thesaurus/Model/Indexer/IndexHandler.php
as well as multiple space/hyphen separating characters.
Please note this only special characters related errors when indexing the thesaurus rules,
but does not offer any warranty that those special characters will be accurately matched
when those rules are applied.
=> Fixes #1728 Special chars support in thesaurus rules

src/module-elasticsuite-catalog/Model/ResourceModel/Product/Fulltext/Collection.php
Hi,
I had a strange issue that the sorting was not applied to the collection. The reason for this is, that the collection has already rendered the filters, without an order. The ordering comes later through the Toolbar Block but it was not applied.
This tiny PR should fix it. 
Thanks for again these awesome module!
\- Thomas
=> Bugfix: Ordering is not applied

src/module-elasticsuite-tracker/etc/adminhtml/system.xml
Primary change is to correct the comment on the field to indicate the true default (365 days, not 30 days). Additionally cleaning up the grammar/consistency of the other comments.
=> Fix tracking retention label for accuracy

src/module-elasticsuite-catalog-graph-ql/DataProvider/Product/LayeredNavigation/Builder/Attribute.php
When querying product aggregations using GraphQL, the returned attribute label is not always the correct one for the requested store view.
The issue is reproducible when the store views IDs are not consecutive.
`Magento\Eav\Model\Entity\Attribute\AbstractAttribute::getFrontendLabels()` returns an array of labels, where the key is numeric, starting from 0, however, `Smile\ElasticsuiteCatalogGraphQl\DataProvider\Product\LayeredNavigation\Builder\Attribute::build()` function is expecting the key to be the store id.
To reproduce:
1. Configure multiple store views where the IDs are not consecutive
2. Set different attribute labels for each store view
3. Use the following graphql query to fetch the aggregations:
```
query getProductFiltersByCategory {
products(filter: { category_id: {eq: "2"} …
```
=> Fix store specific attribute label on GraphQL products aggregations query

src/module-elasticsuite-catalog/Model/ResourceModel/Product/Fulltext/Collection.php
The page size is already reset in _renderFiltersBefore but might be changed between rendering the filters and loading the collection. If that happens no items will be found.
#249
When moving the navigation (`catalog.leftnav`) it will change the load order of the blocks. In our case we moved it in `catalog_category_view_type_layered.xml`:
```xml
<move element="catalog.leftnav" destination="content" before="-"/>
```
When rendering a category view `\Magento\Catalog\Block\Product\ProductList\Toolbar::setCollection` is called multiple times. Within `setCollection` `$this->_collection->setCurPage($this->getCurrentPage());` is called and will overwrite resetting the page size in [_renderFiltersBefore](https://github.com/Smile-SA/elasticsuite/blob/2.8.x/src/module-elasticsuite-catalog/Model/Resour …
=> Reset page size before load

src/module-elasticsuite-catalog/Model/ResourceModel/Product/Fulltext/Collection.php
Magento 2.3.x toolbar does not reset the current page var or re-compute it accurately when changing page size or using 'Show all'.
=> Fixes #1946 #1693 Handling out of bonds page.

src/module-elasticsuite-core/view/frontend/web/js/form-mini.js
if rendered below virtual keyboard (android 7.0)
=> Fixes #1626 Autocomplete not clickable on mobile

src/module-elasticsuite-tracker/view/frontend/web/js/user-consent.js
When merging this file using e.g. magepack, the missing semicolon may cause problems in the file that gets appended. It may try to call define() as a function.
=> Make js compatible to merging with other files.

src/module-elasticsuite-catalog/Plugin/CatalogSearch/ResultPlugin.php
Config was always taken from the default scope, while the option can be configured on store scope.
=> Fix redirect if one result config scope

src/module-elasticsuite-tracker/Block/Variables/Page/Order.php
This pull request contains a check to avoid errors like:
Error: Call to a member function getMethod() on null in /var/www/html/vendor/smile/elasticsuite/src/module-elasticsuite-tracker/Block/Variables/Page/Order.php:74
This could happen when the object returned from the checkout session by [getLastRealOrder](https://github.com/magento/magento2/blob/2.4.1/app/code/Magento/Checkout/Model/Session.php#L531) method is an empty Order class.
=> Added check on fetch order from checkout session

src/module-elasticsuite-core/Api/Client/ClientConfigurationInterface.php, src/module-elasticsuite-core/Client/ClientBuilder.php, src/module-elasticsuite-core/Client/ClientConfiguration.php, src/module-elasticsuite-core/etc/adminhtml/system.xml
Adds support for Basic HTTP Authentication using encoded/encrypted Authorization header. (Open Distro Basic HTTP Authentication requires this when you use the internal users authentication functionality.)
Implements https://github.com/Smile-SA/elasticsuite/issues/2163
=> #2163 Add Basic HTTP Authentication (encrypted) support for Open Distro

src/module-elasticsuite-catalog-rule/Model/Rule/Condition/Product/SpecialAttribute/HasImage.php
Fixes #2230 "Has Image" Rule for Optimizers does not work with images that have no_selection set
Fixed by adding a condition to the generated query that excludes no_selection in addition to the exists clause.
=> bugfix for HasImage filter matching products having no_selection as image value

src/module-elasticsuite-thesaurus/Model/Index.php
When synonyms are saved into a database in all multi-word expressions all spaces are converted to underscore characters.  
However, when a customer is using the search feature on a storefront the conversion does not occur there for it is not finding any results.
For example expression "red jacket" will be saved in the database as "red_jacket" but when searching it will be still looking for "red jacket".
=> Fix #1933 multi word synonyms search

src/module-elasticsuite-catalog/Model/ResourceModel/Product/FilterableAttribute/Category/Collection.php
**Problem**
One of the most expensive calls (according to BlackFire profile), is a triple call for the same data, executed when the Category page is being loaded. To avoid such a situation, I use Object Cache to keep the result of the DB call during the execution.
=> Performance: Add ObjectCache to avoid redundant DB calls

src/module-elasticsuite-catalog/Plugin/Search/Request/Product/Attribute/Aggregation/LayeredNavAttribute.php
This causes our installation to break since we dump the composer autoloader with the `--classmap-authoritative` option
=> Wrong casing (typo) in LayeredNavAttribute namespace

src/module-elasticsuite-virtual-category/Plugin/Rule/ConditionFactoryPlugin.php, src/module-elasticsuite-virtual-category/etc/di.xml
by on-the-fly swapping the rule condition models.
=> Fixes #2338 Support pre-existing PageBuilder widgets (2.8.x)

src/module-elasticsuite-virtual-category/Plugin/Rule/ConditionFactoryPlugin.php, src/module-elasticsuite-virtual-category/etc/di.xml
by on-the-fly swapping the rule condition models.
=> Fixes #2338 Support pre-existing PageBuilder widgets (2.9.x)

src/module-elasticsuite-catalog/Model/Product/Indexer/Fulltext/Datasource/CategoryData.php, src/module-elasticsuite-catalog/Model/Search/Request/Field/Mapper.php, src/module-elasticsuite-catalog/etc/elasticsuite_indices.xml, src/module-elasticsuite-virtual-category/Model/Rule/Condition/Product.php
Update of https://github.com/Smile-SA/elasticsuite/pull/2315.
`category_uid` is the base64 encoded value of `category_id` and not a copy.
- https://devdocs.magento.com/guides/v2.4/graphql/queries/category-list.html
- https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/CatalogGraphQl/Model/Category/Hydrator.php#L66
=> Update category_uid attribute mapping

src/module-elasticsuite-core/etc/elasticsuite_analysis.xml
Explicitly limiting token length to 1/4 of Lucene maximum for text
fields using the keyword analyzer.
=> Fixes #2320 Prevent rejection of documents with large description (2.8.x)

src/module-elasticsuite-core/etc/elasticsuite_analysis.xml
Explicitly limiting token length to 1/4 of Lucene maximum for text
fields using the keyword analyzer.
=> Fixes #2320 Prevent rejection of documents with large description

src/module-elasticsuite-catalog/Model/ResourceModel/Product/Fulltext/Collection.php
to ensure an Elasticsearch request is built and executed in
_renderFiltersBefore if the collection is loaded again.
=> Fixes #2448 force filters re-rendering after clear

src/module-elasticsuite-catalog/Model/ResourceModel/Product/Fulltext/Collection.php
Field filters can be overwritten by using addFieldToFilter with an
identical field name but there might be some situation where removing
one or all field filters is required.
Query filters are stored without a reference but it is now possible to
remove them all on a cloned collection.
=> Fixes #2448 Allowing removal of query/field filter(s)

src/module-elasticsuite-catalog/Model/Product/Indexer/Fulltext/Datasource/CategoryData.php, src/module-elasticsuite-virtual-category/etc/di.xml
For instance, when Smile_ElasticsuiteVirtualCategory is disabled and one
wants to keep products with a '0' position in category at the top of the
category.
Will require changing datasource argument through DI.
=> Feature #2431 Opt. zero product position indexing

src/module-elasticsuite-tracker/Block/Variables/Page/Base.php
In some environments (for example CI/CD) server name value is not set, resulting in:
```
Notice: Undefined index: SERVER_NAME in /var/www/html/vendor/smile/elasticsuite/src/module-elasticsuite-tracker/Block/Variables/Page/Base.php:137.
```
This change uses `requestInterface` to fetch server name if exists, returning empty string otherwise.
=> Fix for missing server name definition

src/module-elasticsuite-core/Index/Mapping/Field.php
The sort order provided in `$direction` can be in uppercase, while the constant is in lowercase. This can create incorrect sort orders, which in our case led to manually sorted products being placed behind the automatically sorted products on virtual category pages. Note: The manually sorted products and automatically sorted products were correctly sorted within their respective groups, but the sort order of the groups was incorrect.
cc @MatthijsBreed
=> [FEATURE][GWSM2-985] - Fixes sort order case sensitivity.

src/module-elasticsuite-core/Api/Cluster/ClusterInfoInterface.php, src/module-elasticsuite-core/Cluster/ClusterInfo.php, src/module-elasticsuite-core/Plugin/Deprecation/Client/ClientPlugin.php, src/module-elasticsuite-core/Plugin/Deprecation/Index/MappingPlugin.php
Adds checks to version comparison functions to support 1.x versioning for OpenSearch to help with 2.4.4 Compatibility - https://github.com/Smile-SA/elasticsuite/issues/2494
Follows some guidelines outlined here - https://github.com/opensearch-project/OpenSearch/issues/693
Checks for a distribution variable in version info returned by search service.
=> 2.4.4 Support (#2494) - Adding base OpenSearch compatibility checks

src/module-elasticsuite-virtual-category/Model/Url.php
When no category URL suffix is defined, the get function returns NULL causing this error: Deprecated Functionality: str_replace(): Passing null to parameter #1 ($search) of type array|string is deprecated
=> Fixed deprecation error in PHP 8.1

src/module-elasticsuite-catalog/Helper/AbstractAttribute.php
Sometimes one of the `$optionTextValues` could be `null`. And in PHP 8 `Passing null to parameter Smile-SA#1 ($string) of type string is deprecated`. So I suggest to explicitly cast all values to string.
=> Fix a deprecation warning (PHP 8.1 compatibility)

src/module-elasticsuite-catalog-graph-ql/DataProvider/Product/LayeredNavigation/Builder/Category.php, src/module-elasticsuite-catalog-graph-ql/DataProvider/Product/LayeredNavigation/Builder/Price.php
Replaces PR #2146 considering that i18n+GraphQL+multiple store views of different locales seems to be a bit wonky.
New approach is to pull frontend labels of the `category_ids` and `price` product attributes so it does not require additional translation strings.
**But** it is also possible to fallback to the pure i18n approach by injecting through the DI empty strings as arguments  
```
<type name="Smile\ElasticsuiteCatalogGraphQl\DataProvider\Product\LayeredNavigation\Builder\Category">
<arguments>
<argument name="attributeCode" xsi:type="string"></argument>
</arguments>
</type>
<type name="Smile\ElasticsuiteCatalogGraphQl\DataProvider\Product\LayeredNavigation\Builder\Price">
<arguments>
<argument name="attributeCode" xsi:type="string"></argument>
</arguments>
</type>
```
PS: …
=> [GraphQL] Translation support for category, price filter labels

src/module-elasticsuite-catalog-rule/Model/Rule/Condition/Product.php
Currently, only the 'price' attribute itself is seen as numeric (and those with input-validation). This means all other attributes put on the 'decimal'/'price' type are seen as a string instead of as a 'numeric'.
This adds an extra check on the frontendInput === 'price'
=> Fix for wrong type casting in Adminhtml of Special Price attribute

src/module-elasticsuite-catalog/etc/adminhtml/di.xml
Change name of virtual factory as it triggers the Magento magic class generation.
Caused error:
```
Source class "\fulltextProductCollectionWithoutAggregations" for "fulltextProductCollectionWithoutAggregationsFactory" generation does not exist.
```
Fixes #2611
=> Change name of virtual factory as it triggers the Magento magic class generation

src/module-elasticsuite-virtual-category/Model/Url.php
Accessing a url that is same as url key for category that exists in
another store will return no rewrite in
`Smile\ElasticsuiteVirtualCategory\Model\Url::getCategoryRewrite`, therefore calling on setRequestPath results in critical error.
This commit checks if rewrite exists before calling setRequestPath.
Resolves #2623
=> Fix calls to setRequestPath on rewrites that may not exist

src/module-elasticsuite-core/view/frontend/web/js/form-mini.js
I've noticed on my magento installation 2.4.3 search requests are appended with `&_=[timestamp]` which makes requests slower than they could be.
[jQuery ajax documentation](https://api.jquery.com/jquery.ajax/#jQuery-ajax-settings) mentions a `cache` option for ajax calls, which controls this behaviour.
The ajax() funtction is called without `cache` parameter making it work kind of automatically as documentation says.
I'm not sure how that exactly is resolving to false - I guess it may be considering dataType beeing 'jsonp' or 'script'. Therefore, in this PR I'm adding a `cache: true` option to make sure the timestamp is not appended as well as I'm setting `dataType: 'json'` to make sure jQuery expects 'json' which is what is beeing returned.
This PR also adds extra space for style …
=> Make jQuery ajax request for autocomplete cacheable

src/module-elasticsuite-core/Api/Client/ClientConfigurationInterface.php, src/module-elasticsuite-core/Client/ClientBuilder.php, src/module-elasticsuite-core/Client/ClientConfiguration.php, src/module-elasticsuite-core/etc/adminhtml/system.xml, src/module-elasticsuite-core/etc/config.xml
Allow for the core client configuration to include configuring the maximum number of retries for requests - this is particularly useful for indexing purposes
=> Add the option to configure the maximum number of request retries for the elasticsearch client

src/module-elasticsuite-catalog/view/adminhtml/web/css/source/_module.less, src/module-elasticsuite-catalog/view/adminhtml/web/template/form/element/product-sorter.html
Description:
When prices are with more than 6 signs and/or products are out of stock (or depends on language with long label) info box growing and break layout.
Actual Results:
Expected Results:
=> Fixes to preview and sorting in admin if prices are with too many signs.

src/module-elasticsuite-catalog/etc/view.xml
This PR fixes blurry images on HiDPI screens.
Here is the screenshot before/after:
=> Use 2x image size to prevent blurry images in search dropdown

src/module-elasticsuite-catalog/view/frontend/web/js/range-slider-widget.js
I'm working on [breezefront integration](https://github.com/breezefront/module-breeze-smile-elasticsuite) and trying to reuse your js files. This file will be fully compatible with breeze with this tiny change.
Here is the bind documentation: https://api.jquery.com/bind/
Thanks!
=> Replace deprecated .bind method with .on (jQuery)

src/module-elasticsuite-catalog/Model/Product/Indexer/Fulltext/Datasource/PriceData.php
In the original PR we get child ids and check they are with discount or not, but without relation with parent product (and it works fine, if parent product and his child products are created after each other). 
Resolve #2853
=> Fix issue #2853 - Add additional logic to map parent and child ids.

src/module-elasticsuite-tracker/Model/IndexResolver.php
Magento 2.4.6, PHP 8.2.3. When you trying to run cron job manually from the list in admin panel, you can see follow error and its description:
This is the fix for the issue.
=> Fix cron error "Deprecation functionality: creation of dynamic property"

src/module-elasticsuite-thesaurus/Plugin/QueryRewrite.php
This resolves the issue #2891
A simple testing scenario for reproducing the issue would be:
Provided that project has a product with SKU `2097402` and the module is configured with the following synonyms:
```
097402,2097402
```
Doing a search for query `097402` will not return any results.
=> Fix numerical-only synonims

src/module-elasticsuite-catalog/Block/Navigation/FilterRenderer.php
This fix prevents wrong behaviour when adding a new filter type on hyva theme / hyva compatibility module. (And I think when html minification is ON)
(May be with luma too, I did not try)
=> Fix filter rendering

src/module-elasticsuite-core/Search/Adapter/Elasticsuite/Spellchecker.php
disabled by error when introducing support of standard_edge_ngram fields in the term vectors request.
=> [Spellchecker] Re-enable spelling type cache

src/module-elasticsuite-core/Client/ClientBuilder.php, src/module-elasticsuite-core/Client/ClientConfiguration.php, src/module-elasticsuite-core/etc/adminhtml/system.xml, src/module-elasticsuite-core/etc/config.xml
Added configuration, default value for it, and elasticsearch call option for SSL Verification. This allows to turn it off, for ES clients like opensearch, on local environments.
=> Added configuration for ssl verification

src/module-elasticsuite-catalog/Model/Attribute/Source/FilterSortOrder.php, src/module-elasticsuite-core/Search/Adapter/Elasticsuite/Request/Aggregation/Builder/Term.php, src/module-elasticsuite-core/Search/Request/BucketInterface.php, src/module-elasticsuite-core/Test/Unit/Search/Adapter/Elasticsuite/Request/Aggregation/Builder/TermTest.php
Deprecated since Elasticsearch 6.0.0 but finally removed in 8.11
=> Fixes #3148 Replacing _term agg sort order by _key

composer.json, src/module-elasticsuite-core/Client/Client.php, src/module-elasticsuite-core/Client/ClientBuilder.php, src/module-elasticsuite-core/Test/Unit/Index/IndexOperationTest.php, src/module-elasticsuite-core/etc/di.xml
This should probably replace #2910 
The Opensearch 2.0 client has been tested working with : 
- ES 7
- ES 8
- Opensearch 2
- ~~Opensearch 1.~~ : tested OK but not supported by Magento as per https://experienceleague.adobe.com/docs/commerce-operations/installation-guide/system-requirements.html
By using the Opensearch client, we are preserved from the FQCN change in the Elasticsearch PHP client, between v7 and v8.
On top of that, the Opensearch client is basically identical to the ES Client, so we're still familiar with it.
=> Replace the Elasticsearch client by the Opensearch client.

src/module-elasticsuite-core/etc/adminhtml/system.xml
Updated comment of enable_certificate_validation field, to make it clearer to the users.
=> update of BO comment LU-140

.github/workflows/02-phpstan.yml, .github/workflows/20-integration.yml
`save-state` and `set-output` commands used in GitHub Actions are deprecated and [GitHub recommends using environment files](https://github.blog/changelog/2023-07-24-github-actions-update-on-save-state-and-set-output-commands/).
This PR updates the usage of `set-output` to `$GITHUB_OUTPUT`
Instructions for envvar usage from GitHub docs:
https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter
=> ci: Use GITHUB_OUTPUT envvar instead of set-output command

src/module-elasticsuite-catalog/Plugin/Index/MappingPlugin.php
Without using the MappingInterface in the plugin you are not able to write your own Mapping integration.
=> mapping plugin - use interface instead of mapping directly

src/module-elasticsuite-virtual-category/Model/Url.php
Hi guys,
I'm presenting you this PR because of an issue we found out in a store of ours.
The issue; in a store we had a virtual category which had a virtual root category set. However the production environment returned a 404 for a specific category within that virtual category.
After a long debug session we narrowed it down to how the category was fetched from the collection. And eventually I found out that if there are multiple categories inside set root category with the same `url_key` the first one will always be fetched. In this particular case we had a category which was disabled and was not intended to be fetched.
So I've added an `addIsActiveFilter()` to the category collection. This helps to fetch only active categories. 
This doesn't entirely solve the issue where you might have …
=> Fix: Add isActiveFilter to prevent disabled categories from being found

src/module-elasticsuite-tracker/Model/EventIndex.php, src/module-elasticsuite-tracker/Model/ResourceModel/EventQueue.php
Belt & Suspenders approach, ensuring the event will be flagged as invalid and not be indexed (but it's implied by the invalid) if store_id is not numeric.
=> Fix #3157 by ensuring store_id is numeric.

composer.json
I'm not sure why these limitation was set for version below 2.0.1, but this reflects to critical errors in magento 2.4.7-beta3 (and probably the final release).
I put the same requirements as they are in the Opensearch module in Magento https://github.com/magento/magento2/blob/b2286ecfb014dbe05a45004526541aa8250259c2/app/code/Magento/OpenSearch/composer.json#L12
=> Change opensearch deps to make it compatible with magento 2.4.7-beta3

src/module-elasticsuite-core/Search/Adapter/Elasticsuite/Request/Query/Builder/MultiMatch.php, src/module-elasticsuite-core/Search/Request/Query/Fulltext/QueryBuilder.php
by moving the logic of applying the fuzziness minimum should match inside the adapter models
=> [Core] Prevent fatal error when fuzziness disabled

src/module-elasticsuite-virtual-category/Model/Rule.php
Since last update: https://github.com/Smile-SA/elasticsuite/commit/9811ee78c0cd430ce2a55fd3e61aaf03db887553#diff-e3d9752e99ca84e5f77b8490a15d16e677f3d2b87e8ce6114cb85513ebb0bc16R180
On lastests: 2.11.6 & 2.10.20
The wrong cast order has a critical impact because it's not the result of the ternary operation that is casted to int bu the condition.
It has a critical impact because it's not possible anymore to use the category condition:
```
[2024-04-23T14:16:34.685022+00:00] report.CRITICAL: TypeError: Smile\ElasticsuiteVirtualCategory\Model\Rule::getFromLocalCache(): Argument #1 ($categoryId) must be of type int, string given, called in /app/fi4jxviizr2zw/vendor/smile/elasticsuite/src/module-elasticsuite-virtual-category/Model/Rule.php on line 191 and defined in …
```
=> Could not load category condition in virtual category conditions: Wrong cast order

src/module-elasticsuite-tracker/view/frontend/templates/config.phtml, src/module-elasticsuite-tracker/view/frontend/templates/variables/page.phtml
According to the CSP updates:
>The default CSP configuration for payment pages for Commerce Admin and storefront areas is now restrict mode. For all other pages, the default configuration is report-only mode. In releases prior to 2.4.7, CSP was configured in report-only mode for all pages.
now an inline scripts should be wrapped using `$secureRenderer` variable in the `.phtml` templates, but for some reason this blocks the work of our Tracker script on Checkout page.
See more:
- https://developer.adobe.com/commerce/php/development/security/content-security-policies/#troubleshooting 
- https://developer.adobe.com/commerce/php/development/security/content-security-policies/#whitelist-an-inline-script-or-style
=> [Tracker] Fix inline script execution on Checkout page according to CSP restrictions

src/module-elasticsuite-catalog/Model/ResourceModel/Product/Fulltext/Collection.php
That can happen when a single collection is used in a loop with different search queries each time.
While the Elasticsearch requests will be correct, the collection will only be correctly hydrated the first time.
Especially visible with a pageSize of 1 and search terms generating specific and non overlapping results sets.
=> [Core] Prevent stacking SQL where prod. id conditions

src/module-elasticsuite-core/Search/Request/Query/Fulltext/QueryBuilder.php
- in \Smile\ElasticsuiteCore\Search\Request\Query\Fulltext\QueryBuilder::create : 
-> move `$spanQuery->setName('SPAN');` after `if` condition
=> Fix Call to a member function setName() on null 

src/module-elasticsuite-thesaurus/Model/Index.php
Since the relevance configuration allows disabling synonyms and/or expansions for a given request type.
=> [Thesaurus] Cache variation according to container name

src/module-elasticsuite-virtual-category/Model/Rule.php
Don't calculate virtual category root if parent category of the root category has been computed.
=> [Virtual Category] Optimize virtual category rule computation

src/module-elasticsuite-core/Setup/ConfigOptionsList.php
This pull request introduces support for configuring OpenSearch settings within the Setup ConfigOptions list in ElasticSuite. By adding this feature, users can now specify OpenSearch-specific configurations, enhancing the flexibility and compatibility of ElasticSuite with OpenSearch.
=> Add Support for OpenSearch Settings in Setup ConfigOptions List

src/module-elasticsuite-core/Search/Request/Query/Filter/QueryBuilder.php
Handles cases where \Magento\CatalogSearch\Model\Advanced::addFilters applies a 'price' condition with a range and an un-necessary 'currency' parameter.
=> [Core] Fix #3334, adding support currency condition

src/module-elasticsuite-catalog-graph-ql/Model/Resolver/Products.php, src/module-elasticsuite-catalog-graph-ql/Model/Resolver/Products/Query/Search.php, src/module-elasticsuite-catalog-graph-ql/Model/Resolver/Products/SearchResult.php, src/module-elasticsuite-catalog-graph-ql/etc/schema.graphqls, src/module-elasticsuite-core/Model/Search.php, src/module-elasticsuite-core/Test/Unit/Model/SearchTest.php
In order to send it to the tracker in headless mode
=> [Tracking] Add query id in graphQL search response

src/module-elasticsuite-core/Search/Adapter/Elasticsuite/Spellchecker.php, src/module-elasticsuite-core/Test/Unit/Search/Adapter/Elasticsuite/SpellcheckerTest.php
To avoid false 'exact' matches on leading parts of a misspelled word. The logic is similar to the use of a distinct 'search_analyzer' on fields using 'standard_edge_ngram' as 'analyzer'.
=> [Core] No edge ngram decomposition in termVectors

src/module-elasticsuite-catalog/etc/mview.xml
which force a catalogsearch_fulltext reindex after the inventory has changes
=> [CatalogSearch] Forcefull add mview trigger removed in 2.4.6

src/module-elasticsuite-core/Search/Request/SortOrder/SortOrderBuilder.php
It should be possible to provide a value programmatically for the `missing` parameter on sort orders.
This PR allows that while preserving the previous behaviour for compatibility.
=> Allow providing a value for "missing" values in sort order params

src/module-elasticsuite-virtual-category/Helper/Rule.php, src/module-elasticsuite-virtual-category/Model/Rule.php
If we use this cached query we will build a category query with many useless clauses as the optimization of the method \Smile\ElasticsuiteVirtualCategory\Model\Rule::isVirtualCategoryRootInExcludeCategories will be avoided
=> [Virtual Category] Prevent using cached query for sub virtual category

src/module-elasticsuite-catalog-graph-ql/Model/Resolver/Products/Query/Search.php, src/module-elasticsuite-catalog-rule/Test/Unit/Model/Rule/Condition/Product/SpecialAttributeProviderTest.php, src/module-elasticsuite-core/Search/Request/Query/Vector/Opensearch/Neural.php, src/module-elasticsuite-thesaurus/Test/Unit/Plugin/QueryRewriteTest.php
=> [Compat] Fixes Smile-SA#3578 PHP 8.4 deprecation: Implicitly marking parameter as nullable is deprecated

src/module-elasticsuite-core/Api/Client/ClientInterface.php, src/module-elasticsuite-core/Client/Client.php, src/module-elasticsuite-indices/Model/IndexStatsProvider.php
Changes 
* One single request for all indices instead of one request per index
* Single cache entry
* Only desired settings grabbed
I could have even removed the use of the system cache and opted for pure memory cache, but let's do one step at a time
=> [Indices] #3592 #3596 Better performance when getting indices stats

src/module-elasticsuite-catalog/Model/Eav/Indexer/Fulltext/Datasource/AbstractAttributeData.php
Fixing issue:
https://github.com/Smile-SA/elasticsuite/issues/3617
=> fix: [3617] Elasticsuite is not indexing url_key in Magento 2.4.8

src/module-elasticsuite-tracker/Model/Event/Mapping/TypeEnforcer/Integer.php
Useful if a headless theme sends a product uid instead of id, category uid instead of id, etc: will avoid those identifiers to be transformed as '0' when forcefully casted as int.
=> [Tracker] Handle base64 encoded numeric identifiers
