src/module-elasticsuite-catalog/view/adminhtml/layout/catalog_product_attribute_edit.xml
src/module-elasticsuite-catalog/view/adminhtml/layout/catalog_product_attribute_edit_popup.xml
src/module-elasticsuite-catalog/view/adminhtml/templates/catalog/product/attribute/js.phtml
src/module-elasticsuite-swatches/view/adminhtml/layout/catalog_product_attribute_edit.xml
src/module-elasticsuite-swatches/view/adminhtml/layout/catalog_product_attribute_edit_popup.xml
src/module-elasticsuite-swatches/view/adminhtml/templates/catalog/product/attribute/js.phtml

Done two-way for modular dependency : 
- in standard catalog module
- in swatches module

Feature facet varchars attributes

---

src/module-elasticsuite-catalog/Block/Navigation/Renderer/PriceSlider.php
src/module-elasticsuite-catalog/Block/Navigation/Renderer/Slider.php
src/module-elasticsuite-catalog/Block/Plugin/Adminhtml/Product/Attribute/Edit/Tab/FrontPlugin.php
src/module-elasticsuite-catalog/Model/Layer/Filter/Decimal.php
src/module-elasticsuite-catalog/Model/Layer/Filter/DecimalFilterTrait.php
src/module-elasticsuite-catalog/Model/Layer/Filter/Price.php
src/module-elasticsuite-catalog/Model/Layer/FilterList.php
src/module-elasticsuite-catalog/Setup/UpgradeSchema.php
src/module-elasticsuite-catalog/etc/frontend/di.xml
src/module-elasticsuite-catalog/etc/module.xml
src/module-elasticsuite-catalog/view/frontend/layout/catalog_category_view_type_layered.xml
src/module-elasticsuite-catalog/view/frontend/layout/catalogsearch_result_index.xml
src/module-elasticsuite-catalog/view/frontend/templates/layer/filter/slider.phtml
src/module-elasticsuite-catalog/view/frontend/web/css/source/_module.less
src/module-elasticsuite-catalog/view/frontend/web/js/range-slider-widget.js

Feature facet decimal

---

src/module-elasticsuite-catalog/Helper/Attribute.php
src/module-elasticsuite-catalog/Model/Category/Indexer/Fulltext.php
src/module-elasticsuite-catalog/Model/Category/Indexer/Fulltext/Action/Full.php
src/module-elasticsuite-catalog/Model/Category/Indexer/Fulltext/Datasource/AttributeData.php
src/module-elasticsuite-catalog/Model/Category/Indexer/IndexerHandler.php
src/module-elasticsuite-catalog/Model/Eav/Indexer/Fulltext/Datasource/AbstractAttributeData.php
src/module-elasticsuite-catalog/Model/Eav/Indexer/IndexerHandler.php
src/module-elasticsuite-catalog/Model/Product/Indexer/Fulltext/Datasource/AttributeData.php
src/module-elasticsuite-catalog/Model/ResourceModel/Category/Indexer/Fulltext/Action/Full.php
src/module-elasticsuite-catalog/Model/ResourceModel/Eav/Indexer/AbstractIndexer.php
src/module-elasticsuite-catalog/Model/ResourceModel/Eav/Indexer/Fulltext/Datasource/AbstractAttributeData.php
src/module-elasticsuite-catalog/Model/ResourceModel/Product/Indexer/Fulltext/Action/Full.php
src/module-elasticsuite-catalog/Model/ResourceModel/Product/Indexer/Fulltext/Datasource/AttributeData.php
src/module-elasticsuite-catalog/Model/ResourceModel/Product/Indexer/Fulltext/Datasource/CategoryData.php
src/module-elasticsuite-catalog/Model/ResourceModel/Product/Indexer/Fulltext/Datasource/InventoryData.php
src/module-elasticsuite-catalog/Model/ResourceModel/Product/Indexer/Fulltext/Datasource/PriceData.php
src/module-elasticsuite-catalog/Plugin/Indexer/Category/Save/ReindexCategoryAfterSave.php
src/module-elasticsuite-catalog/etc/di.xml
src/module-elasticsuite-catalog/etc/elasticsuite_indices.xml
src/module-elasticsuite-catalog/etc/indexer.xml
src/module-elasticsuite-catalog/etc/mview.xml

This is a proposal of implementation.
- categories get stored in an other per-store index : catalog_category_store_HHHH:etc...
- product's centric parts of indexation have been revamped to a generic behavior (EAV philosophy) to handle easily categories attributes indexation.
Feel free to communicate any remark about this.

Fulltext indexer for categories.

---

src/module-elasticsuite-core/Search/Adapter/ElasticSuite/Request/Query/Builder.php
src/module-elasticsuite-core/Search/Adapter/ElasticSuite/Request/Query/Builder/Boolean.php
src/module-elasticsuite-core/Search/Request/Query/Boolean.php
src/module-elasticsuite-core/Search/Request/Query/QueryFactory.php

Work around to issue #18, low impact.

Renamed Bool to Boolean #18

---

src/module-elasticsuite-catalog-rule/composer.json
src/module-elasticsuite-tracker/composer.json
src/module-elasticsuite-virtual-category/composer.json

The dependency was missing in some modules.

Add magento/framework to composer requirements of modules.

---

src/module-elasticsuite-catalog/Model/Product/Indexer/Fulltext/Datasource/AttributeData.php

I refactored the whole code.
This PR will be merged instead of the #64 one.

Fix #60 : child attributes indexed when not already present into the child product.

---

src/module-elasticsuite-catalog/Setup/InstallSchema.php

Will fix #102 
Should be also deployed to 2.2.x

Remove unneeded constructor and property in Schema install class.

---

src/module-elasticsuite-catalog/i18n/en_US.csv

This will fix #84 
Should be merged to 2.2x too.

Reword the english translation of the approaching search results phrase.

---

src/module-elasticsuite-catalog/Plugin/Indexer/Category/Save/ReindexCategoryAfterSave.php
src/module-elasticsuite-catalog/etc/mview.xml

Should close #107 .
To merge on master & also 2.2.x

Fix categories scheduled indexing

---

src/module-elasticsuite-core/view/frontend/web/js/form-mini.js

Proposal of implementation of my own issue #113 
Tell me if it's worth it or not.

Ability to kill previous autocomplete queries on the fly.

---

src/module-elasticsuite-catalog/Block/Navigation.php
src/module-elasticsuite-catalog/Model/ResourceModel/Eav/Indexer/Fulltext/Datasource/AbstractAttributeData.php
src/module-elasticsuite-catalog/Model/ResourceModel/Eav/Indexer/Indexer.php
src/module-elasticsuite-catalog/Model/ResourceModel/Product/Indexer/Fulltext/Datasource/AttributeData.php
src/module-elasticsuite-catalog/Model/ResourceModel/Product/Indexer/Fulltext/Datasource/CategoryData.php
src/module-elasticsuite-catalog/Model/ResourceModel/Product/Indexer/Fulltext/Datasource/InventoryData.php
src/module-elasticsuite-catalog/Setup/InstallData.php
src/module-elasticsuite-catalog/etc/di.xml
src/module-elasticsuite-catalog/etc/frontend/di.xml
src/module-elasticsuite-catalog/view/frontend/layout/catalog_category_view_type_layered.xml
src/module-elasticsuite-catalog/view/frontend/layout/catalogsearch_result_index.xml

@afoucret can you review this one please ?

Feature staging implementation

---

src/module-elasticsuite-virtual-category/etc/config.xml

Disabling the module output is enough to prevent any troubles.

Disable output of the Magento_VisualMerchandiser module.

---

src/module-elasticsuite-catalog/Model/Autocomplete/Category/DataProvider.php
src/module-elasticsuite-catalog/Model/Autocomplete/Category/ItemFactory.php
src/module-elasticsuite-catalog/Model/ResourceModel/Category/Fulltext/Collection.php
src/module-elasticsuite-catalog/Setup/UpgradeData.php
src/module-elasticsuite-catalog/etc/adminhtml/system.xml
src/module-elasticsuite-catalog/etc/config.xml
src/module-elasticsuite-catalog/etc/elasticsuite_search_request.xml
src/module-elasticsuite-catalog/etc/frontend/di.xml
src/module-elasticsuite-catalog/etc/module.xml
src/module-elasticsuite-catalog/i18n/en_US.csv
src/module-elasticsuite-catalog/i18n/fr_FR.csv
src/module-elasticsuite-catalog/view/frontend/web/css/source/_module.less
src/module-elasticsuite-catalog/view/frontend/web/template/autocomplete/category.html

Categories autocomplete implementation.
Produces results like this : 
To merge in 2.2.x to fix #105

Categories autocomplete implementation.

---

src/module-elasticsuite-catalog/Observer/RedirectIfOneResult.php
src/module-elasticsuite-catalog/etc/adminhtml/system.xml
src/module-elasticsuite-catalog/etc/config.xml
src/module-elasticsuite-catalog/etc/events.xml
src/module-elasticsuite-catalog/i18n/en_US.csv
src/module-elasticsuite-catalog/i18n/fr_FR.csv

This is a proposal of implementation for #16 
@afoucret can you review it ?

Adding the ability to redirect to product page if only one result

---

src/module-elasticsuite-catalog/Model/Layer/Filter/Item/Category.php

Now reset others filters.
Fix #132

Fix category filter inconsistent beahvior in fulltext search.

---

src/module-elasticsuite-core/Model/Search/Request/RelevanceConfig/Structure/Element/Section.php

Fix proposal for #134 
But since I do not have the problem locally, I cannot ensure it fixes it... But it does not break anything and the platform is working fine in developer and production mode.

Adding an alias for the Section Visibility usage.

---

src/module-elasticsuite-catalog/Model/Autocomplete/Category/ItemFactory.php

Fix category name retrieval when using flat catalog.

---

src/module-elasticsuite-core/Index/Bulk/BulkRequest.php

Hello @afoucret 
To be merged later, not urgent but was needed for current project.

Bulk Update implementation.

---

src/module-elasticsuite-catalog/Helper/Attribute.php
src/module-elasticsuite-catalog/Model/Product/Indexer/Fulltext/Action/Full.php
src/module-elasticsuite-catalog/Model/ResourceModel/Product/Indexer/Fulltext/Action/Full.php
src/module-elasticsuite-catalog/etc/elasticsuite_indices.xml
src/module-elasticsuite-core/Api/Index/Mapping/FieldInterface.php
src/module-elasticsuite-core/Helper/Cache.php
src/module-elasticsuite-core/Index/IndexSettings.php
src/module-elasticsuite-core/Index/Mapping.php
src/module-elasticsuite-core/Index/Mapping/Field.php
src/module-elasticsuite-core/Indexer/GenericIndexerHandler.php
src/module-elasticsuite-core/Search/Adapter/Elasticsuite/Adapter.php
src/module-elasticsuite-core/Search/Adapter/Elasticsuite/Request/Query/Builder/Boolean.php
src/module-elasticsuite-core/Search/Adapter/Elasticsuite/Spellchecker.php
src/module-elasticsuite-core/Search/Request/Query/Boolean.php
src/module-elasticsuite-core/Search/Request/Query/Fulltext/QueryBuilder.php
src/module-elasticsuite-core/etc/config.xml
src/module-elasticsuite-core/etc/elasticsuite_analysis.xml
src/module-elasticsuite-thesaurus/Model/Index.php
src/module-elasticsuite-thesaurus/Model/Indexer/IndexHandler.php
src/module-elasticsuite-virtual-category/Model/Layer/Filter/Category.php
src/module-elasticsuite-virtual-category/Model/Rule.php

Global performance improvement :
* Better mappings with removed useless analyzed fields and more control on memory usage
* Better usage of the index settings during full indexing
* Magento caching layer for spellcheck, thesaurus and virtual category rules
* Enforce complex queries caching (eg. bool) for the virtual rules ES filters
* PHP optimization for the option value mapping
* Better SQL loading

Feature performance

---

src/module-elasticsuite-catalog/Model/Autocomplete/Product/DataProvider.php
src/module-elasticsuite-catalog/Model/Autocomplete/Product/ItemFactory.php
src/module-elasticsuite-catalog/etc/view.xml

Use resized image for product autocomplete

---

src/module-elasticsuite-catalog-rule/Model/Rule/Condition/Product.php
src/module-elasticsuite-catalog-rule/Model/Rule/Condition/Product/QueryBuilder.php
src/module-elasticsuite-catalog/Model/Product/Indexer/Fulltext/Datasource/PriceData.php
src/module-elasticsuite-catalog/Setup/InstallSchema.php
src/module-elasticsuite-catalog/Setup/UpgradeData.php
src/module-elasticsuite-catalog/etc/module.xml
src/module-elasticsuite-core/Search/Request/Query/QueryFactory.php
src/module-elasticsuite-virtual-category/Model/Rule/Condition/Product.php

Add has_image, is_in_stock and is_discount attributes into virtual rules

Virtual rules special attributes

---

src/module-elasticsuite-catalog/Model/Autocomplete/Category/ItemFactory.php
src/module-elasticsuite-catalog/Model/Autocomplete/Product/ItemFactory.php

Fixup html entities decoding in autocomplete providers.

---

src/module-elasticsuite-core/view/frontend/web/js/form-mini.js

This one may need to publish static-data again to work.

Fix autocomplete navigation

---

src/module-elasticsuite-virtual-category/Api/Data/VirtualRuleInterface.php
src/module-elasticsuite-virtual-category/Model/Rule.php
src/module-elasticsuite-virtual-category/etc/extension_attributes.xml

Will fix #186 
To be merged into 2.2.x, 2.3.x and master.

Move the virtual_rule as an extension attribute to prevent API failures.

---

src/module-elasticsuite-virtual-category/Model/Category/Attribute/Backend/VirtualRule.php

Fix beforeSave virtual categories unserialize

Fix beforeSave virtual categories unserialize

---

src/module-elasticsuite-catalog/Model/ResourceModel/Product/Advanced/Collection.php
src/module-elasticsuite-catalog/etc/di.xml
src/module-elasticsuite-core/Search/Request/Query/Filter/QueryBuilder.php

With the less possible (duplicated) code : but implies to remove the explicit check on $field->isFilterable() on the Query Builder to achieve.
Let me know

Append Advanced Search Compatibility

---

src/module-elasticsuite-virtual-category/Plugin/Catalog/Category/FlatPlugin.php
src/module-elasticsuite-virtual-category/etc/frontend/di.xml

This one should fix #187 which is related to Flat Categories usage.

Fixing proper loading of virtual rules when using flat category index.

---

src/module-elasticsuite-catalog-rule/Block/Product/Conditions.php
src/module-elasticsuite-virtual-category/Model/Layer/Filter/Category.php
src/module-elasticsuite-virtual-category/Model/Preview.php
src/module-elasticsuite-virtual-category/Model/Rule.php
src/module-elasticsuite-virtual-category/Model/Rule/Condition/Product.php

Virtual categories behavior is now the same than normal categories (anchored displaying all chilren categories products).

Fix #230 - Virtual categories behavior

---

src/module-elasticsuite-catalog/Helper/Attribute.php

fix attribute storeId null by set attribute store id after load attribute.

set attribute store id after load attribute

---

src/module-elasticsuite-catalog/view/frontend/web/js/attribute-filter.js
src/module-elasticsuite-catalog/view/frontend/web/js/autocomplete/product-attribute.js
src/module-elasticsuite-core/view/frontend/web/js/form-mini.js

Just some code cleaning on JS files.

Javascript code cleaning

---

src/module-elasticsuite-catalog/view/frontend/web/template/autocomplete/product-attribute.html

Tell me if you prefer to merge this on 2.3 or if I have to rebase on 2.4.
Regards

Hiding product count for attributes autocomplete.

---

src/module-elasticsuite-catalog/Model/ResourceModel/Product/Advanced/Collection.php

Append proper callback for filtering advanced search conditions.

---

src/module-elasticsuite-catalog/view/frontend/web/css/source/_module.less

Displaying the collapse arrow properly when fields are expanded.

---

src/module-elasticsuite-catalog/Model/ResourceModel/Product/Fulltext/Collection.php

Fixing correct appliance of pagination

---

src/module-elasticsuite-catalog-optimizer/Setup/InstallSchema.php
src/module-elasticsuite-catalog-optimizer/Setup/OptimizerSetup.php
src/module-elasticsuite-catalog/Setup/CatalogSetup.php
src/module-elasticsuite-catalog/Setup/InstallData.php
src/module-elasticsuite-catalog/Setup/InstallSchema.php
src/module-elasticsuite-catalog/Setup/UpgradeData.php
src/module-elasticsuite-catalog/Setup/UpgradeSchema.php
src/module-elasticsuite-core/Setup/CoreSetup.php
src/module-elasticsuite-core/Setup/InstallSchema.php
src/module-elasticsuite-thesaurus/Setup/ThesaurusSetup.php
src/module-elasticsuite-thesaurus/Setup/UpgradeSchema.php
src/module-elasticsuite-virtual-category/Setup/InstallData.php
src/module-elasticsuite-virtual-category/Setup/InstallSchema.php
src/module-elasticsuite-virtual-category/Setup/UpgradeData.php
src/module-elasticsuite-virtual-category/Setup/VirtualCategorySetup.php

As we have seen together, here is a complete refactoring of Install/Upgrade classes to ensure the same procedure is ran for a fresh install than when updating an existing one.

Setup refactoring

---

src/module-elasticsuite-catalog/Helper/Attribute.php
src/module-elasticsuite-catalog/Model/Layer/Filter/Attribute.php

Fix zero option labels for attributes

---

src/module-elasticsuite-virtual-category/view/adminhtml/web/js/component/catalog/category/form/assign-products.js

Ensure the "select all" checkbox is not added with other products.

---

src/module-elasticsuite-catalog-optimizer/Controller/Adminhtml/Optimizer/Preview.php
src/module-elasticsuite-catalog-optimizer/Model/Optimizer/ApplierList.php
src/module-elasticsuite-catalog-optimizer/Model/Optimizer/Collection/Provider/DefaultProvider.php
src/module-elasticsuite-catalog-optimizer/Model/Optimizer/Collection/Provider/Exclude.php
src/module-elasticsuite-catalog-optimizer/Model/Optimizer/Collection/Provider/Only.php
src/module-elasticsuite-catalog-optimizer/Model/Optimizer/Collection/Provider/Replace.php
src/module-elasticsuite-catalog-optimizer/Model/Optimizer/Collection/ProviderFactory.php
src/module-elasticsuite-catalog-optimizer/Model/Optimizer/Collection/ProviderInterface.php
src/module-elasticsuite-catalog-optimizer/Model/Optimizer/Preview.php
src/module-elasticsuite-catalog-optimizer/Model/Optimizer/Preview/CategoryQuery.php
src/module-elasticsuite-catalog-optimizer/Model/Optimizer/Preview/Item.php
src/module-elasticsuite-catalog-optimizer/Model/Optimizer/Preview/RequestBuilder.php
src/module-elasticsuite-catalog-optimizer/Model/Optimizer/Preview/ResultsBuilder.php
src/module-elasticsuite-catalog-optimizer/Model/Optimizer/Preview/SearchQuery.php
src/module-elasticsuite-catalog-optimizer/Model/Search/Request/Product/Source/Containers.php
src/module-elasticsuite-catalog-optimizer/Ui/Component/Optimizer/Form/DataProvider.php
src/module-elasticsuite-catalog-optimizer/etc/di.xml
src/module-elasticsuite-catalog-optimizer/i18n/en_US.csv
src/module-elasticsuite-catalog-optimizer/i18n/fr_FR.csv
src/module-elasticsuite-catalog-optimizer/view/adminhtml/templates/optimizer/preview.phtml
src/module-elasticsuite-catalog-optimizer/view/adminhtml/ui_component/smile_elasticsuite_catalog_optimizer_form.xml
src/module-elasticsuite-catalog-optimizer/view/adminhtml/web/css/source/_module.less
src/module-elasticsuite-catalog-optimizer/view/adminhtml/web/js/components/form/optimizer/optimizer-preview-type.js
src/module-elasticsuite-catalog-optimizer/view/adminhtml/web/js/components/form/optimizer/optimizer-preview.js
src/module-elasticsuite-catalog-optimizer/view/adminhtml/web/js/components/form/optimizer/preview/item.js
src/module-elasticsuite-catalog-optimizer/view/adminhtml/web/template/form/element/optimizer-preview.html

Hello @afoucret ,
let me know about this one.
It was quite hard to inject conditionnally the optimizers because of the existing plugin who does it on a very low-level (on the QueryBuilder).
Maybe we could consider moving this plugin elsewhere which could allow me to write smaller piece of code for this feature.
Let me know

Feature optimizer preview

---

src/module-elasticsuite-catalog/etc/frontend/di.xml
src/module-elasticsuite-catalog/view/frontend/layout/default.xml
src/module-elasticsuite-core/Block/Search/Form/Autocomplete.php
src/module-elasticsuite-core/etc/frontend/di.xml
src/module-elasticsuite-core/i18n/en_US.csv
src/module-elasticsuite-core/i18n/fr_FR.csv
src/module-elasticsuite-core/view/frontend/layout/default.xml

Fixing the way the translations of the autocomplete  are built.

---

src/module-elasticsuite-catalog/Model/ResourceModel/Product/Fulltext/Collection.php

Ensure proper value for pageSize is reset after load.

---

src/module-elasticsuite-tracker/view/frontend/web/js/tracking.js

 Fixing JS error when tracking is disabled.

---

src/module-elasticsuite-core/view/frontend/web/js/form-mini.js

As suggested in #433 
Just using the debounce function from underscore.js instead of copy pasting it as proposed.

Adding debounce to autocomplete.

---

src/module-elasticsuite-catalog/Model/Product/Indexer/Fulltext/Datasource/AttributeData.php
src/module-elasticsuite-catalog/Model/ResourceModel/Product/Indexer/Fulltext/Datasource/AttributeData.php

Fix children visibility during product indexing.

---

src/module-elasticsuite-swatches/view/adminhtml/layout/catalog_product_attribute_edit_popup.xml

Fixing incorrect layout used in new attribute popup.

---

src/module-elasticsuite-virtual-category/Model/Preview/Item.php
src/module-elasticsuite-virtual-category/etc/view.xml

Use resize when displaying products into virtual categories preview.

---

src/module-elasticsuite-catalog/Model/Product/Indexer/Fulltext/Datasource/AttributeData.php

Solves https://github.com/Smile-SA/elasticsuite/issues/533

Always reset array keys after adding attributes gathered from children products

---

src/module-elasticsuite-catalog/view/adminhtml/web/css/source/_module.less
src/module-elasticsuite-catalog/view/adminhtml/web/js/form/element/product-sorter/item.js
src/module-elasticsuite-catalog/view/adminhtml/web/template/form/element/product-sorter.html
src/module-elasticsuite-virtual-category/Model/Preview/Item.php

Add title to product name and sku on product sorter admin component

---

src/module-elasticsuite-core/Model/Search/Request/RelevanceConfig.php
src/module-elasticsuite-core/Model/Search/Request/RelevanceConfig/ReaderPool.php
src/module-elasticsuite-core/Search/Request/RelevanceConfig/App/Config.php
src/module-elasticsuite-core/Search/Request/RelevanceConfig/App/Config/ScopePool.php
src/module-elasticsuite-core/etc/di.xml

This PR contains the fixes to remain compliant with Magento 2.2 CE and EE (which should be release this week).
This has been tested as backward-compatible with Magento 2.1.9.
Since it's backward-compatible we could merge it to 2.3.x to release a Magento 2.2 compatible version quickly.
Let me know if you prefer to see it on another branch.

Magento 2.2 Compatibility

---

src/module-elasticsuite-catalog/Model/Layer/Filter/Attribute.php

Fix admin sort index.

---

src/module-elasticsuite-core/Search/Adapter/Elasticsuite/Spellchecker.php

Fix term vectors on empty indices.

---

src/module-elasticsuite-catalog/Model/Product/Indexer/Fulltext/Datasource/AttributeData.php

Fix empty children status.

---

src/module-elasticsuite-tracker/view/frontend/web/js/tracking.js

Fix error in tracker when GA params are present.

---

src/module-elasticsuite-virtual-category/Model/Preview.php

Filter Virtual category preview with proper visibilities.

---

src/module-elasticsuite-catalog/etc/elasticsuite_search_request.xml
src/module-elasticsuite-catalog/etc/frontend/di.xml

* Remove unused `advanced_search_container` search container
* Append a search container for product autocomplete `catalog_product_autocomplete`
* Rewording for `category_search_container` label

Clean search containers.

---

src/module-elasticsuite-catalog/Block/Plugin/ResultPlugin.php

Do not update count when a filter is used.

Fix search results count in Magento reports.

---

src/module-elasticsuite-catalog/view/frontend/web/css/source/_module.less
src/module-elasticsuite-catalog/view/frontend/web/js/attribute-filter.js
src/module-elasticsuite-catalog/view/frontend/web/template/attribute-filter.html

Facet search autocomplete.

---

composer.json
src/module-elasticsuite-catalog-optimizer/composer.json
src/module-elasticsuite-catalog-rule/composer.json
src/module-elasticsuite-catalog/composer.json
src/module-elasticsuite-catalog/i18n/en_US.csv
src/module-elasticsuite-catalog/i18n/fr_FR.csv
src/module-elasticsuite-catalog/view/frontend/web/js/attribute-filter.js
src/module-elasticsuite-core/composer.json
src/module-elasticsuite-swatches/composer.json
src/module-elasticsuite-thesaurus/composer.json
src/module-elasticsuite-tracker/composer.json
src/module-elasticsuite-virtual-category/composer.json

Updated composer.json with proper requirements, and proper module version.
Adding missing i18n and fixed a ```<b>``` markup that was not closed.

Fix release 24 checklist

---

src/module-elasticsuite-catalog/Helper/AbstractAttribute.php
src/module-elasticsuite-catalog/Helper/Autocomplete.php
src/module-elasticsuite-catalog/Helper/CategoryAttribute.php
src/module-elasticsuite-catalog/Helper/ProductAttribute.php
src/module-elasticsuite-catalog/Model/Eav/Indexer/Fulltext/Datasource/AbstractAttributeData.php
src/module-elasticsuite-catalog/Model/Layer/Filter/Attribute.php
src/module-elasticsuite-catalog/etc/di.xml
src/module-elasticsuite-core/etc/di.xml

Fix DI generation.

---

src/module-elasticsuite-swatches/etc/di.xml

Product empty product list when multiple values are selected

Fix swatches in 2.2.

---

src/module-elasticsuite-catalog-rule/Model/Rule/Condition/Product.php

Fixing class reference issue on Magento EE.

---

src/module-elasticsuite-catalog/Model/ResourceModel/Product/Indexer/Fulltext/Datasource/AttributeData.php

Fix group statement used to get bundle products data to index

---

src/module-elasticsuite-catalog/view/frontend/web/template/attribute-filter.html

Fix #657 
To be merged also in master.

Prevent facet autocomplete search field to have duplicated ids.

---

src/module-elasticsuite-catalog/Model/Autocomplete/Product/Attribute/DataProvider.php

Fix #660 : fatal error in attribute autocomplete.

---

src/module-elasticsuite-catalog/view/frontend/web/js/attribute-filter.js
src/module-elasticsuite-catalog/view/frontend/web/template/attribute-filter.html

- Disable browser autocomplete in search fields
- Add id and label for input checkboxes

Improve attribute filter template.

---

src/module-elasticsuite-core/Helper/IndexSettings.php
src/module-elasticsuite-core/Index/IndexSettings.php

* enable best_compression
* per shard max result window
* code style

Better index settings

---

src/module-elasticsuite-catalog/Controller/Navigation/Filter/Ajax.php
src/module-elasticsuite-catalog/Model/Category/Attribute/Source/FilterDisplayMode.php
src/module-elasticsuite-catalog/Model/Layer/Category/FilterableAttributeList.php
src/module-elasticsuite-catalog/Model/Layer/RelevantFilterList.php
src/module-elasticsuite-catalog/Model/ResourceModel/Product/FilterableAttribute/Category/Collection.php
src/module-elasticsuite-catalog/Setup/CatalogSetup.php
src/module-elasticsuite-catalog/Setup/InstallSchema.php
src/module-elasticsuite-catalog/Setup/UpgradeSchema.php
src/module-elasticsuite-catalog/etc/frontend/di.xml
src/module-elasticsuite-catalog/etc/module.xml

Facet config by category.

---

src/module-elasticsuite-catalog/Model/Layer/Filter/Attribute.php

Fix #677 
To be merged and cascaded into master.

Trim option values when re-sorting them

---

src/module-elasticsuite-catalog/view/adminhtml/web/js/form/element/product-sorter.js
src/module-elasticsuite-catalog/view/adminhtml/web/template/form/element/product-sorter.html
src/module-elasticsuite-virtual-category/Plugin/Catalog/Category/DataProviderPlugin.php

Fix creating subcategory under a root category that is not assigned to any store.

---

src/module-elasticsuite-catalog/Block/Navigation/Renderer/AbstractRenderer.php
src/module-elasticsuite-catalog/Block/Navigation/Renderer/Attribute.php
src/module-elasticsuite-catalog/Block/Navigation/Renderer/Slider.php
src/module-elasticsuite-catalog/view/frontend/web/js/attribute-filter.js
src/module-elasticsuite-catalog/view/frontend/web/template/attribute-filter.html
src/module-elasticsuite-swatches/Block/Navigation/Renderer/Swatches.php

Fix #711 : Do not show product count if disabled in config.

---

src/module-elasticsuite-catalog/Block/Navigation/Renderer/PriceSlider.php
src/module-elasticsuite-catalog/Model/Layer/Filter/Price.php
src/module-elasticsuite-catalog/view/frontend/web/js/range-slider-widget.js

This one fix #696 
Tested on a website with USD, GBP, EUR and XOF (franc CFA).

Allow price slider to support multiple currencies.

---

src/module-elasticsuite-core/view/frontend/web/js/form-mini.js

Add 'processing' class to the autocomplete search form when searching.

---

src/module-elasticsuite-core/Setup/ConfigOptionsList.php

To be merged in 2.5 and cascaded into master.
Regards

Remove trailing space in config path.

---

src/module-elasticsuite-core/Index/IndexSettings.php

Increase ES default max field per index limit.

---

src/module-elasticsuite-catalog/view/adminhtml/web/css/source/_module.less
src/module-elasticsuite-catalog/view/adminhtml/web/js/form/element/product-sorter.js
src/module-elasticsuite-catalog/view/adminhtml/web/template/form/element/product-sorter.html

More compact display + bug with alignment

UX improvement for the product sorter

---

src/module-elasticsuite-catalog/Model/Product/Indexer/Fulltext/Datasource/CategoryData.php
src/module-elasticsuite-catalog/Model/Product/Indexer/Fulltext/Datasource/SearchPositionData.php
src/module-elasticsuite-catalog/Model/ResourceModel/Product/Search/Position.php
src/module-elasticsuite-catalog/etc/elasticsuite_indices.xml
src/module-elasticsuite-virtual-category/Model/ResourceModel/Product/Indexer/Fulltext/Datasource/CategoryData.php

Maybe I can wait for a fix on #756 and then rebase this one.
Let me know.

Add blacklist related fields to ES index.

---

src/module-elasticsuite-core/Search/Request/Aggregation/AggregationBuilder.php
src/module-elasticsuite-core/Search/Request/SortOrder/SortOrderBuilder.php

Do not assume the generated query type is always the same.

Fix nested filter in agg and sort orders.

---

src/module-elasticsuite-catalog/Model/Product/Indexer/Fulltext/Datasource/AttributeData.php
src/module-elasticsuite-catalog/Model/ResourceModel/Product/Indexer/Fulltext/Datasource/AttributeData.php

Fix #791 
I just added children SKUs to the parent document one, as seen together.
Regards

Compute children SKUs into parent product.

---

src/module-elasticsuite-catalog/etc/elasticsuite_search_request.xml
src/module-elasticsuite-catalog/etc/frontend/di.xml

Use quick search container instead of a specific one for product autocomplete

---

src/module-elasticsuite-catalog/Model/Autocomplete/Product/Collection/Filter.php
src/module-elasticsuite-catalog/etc/elasticsuite_search_request.xml
src/module-elasticsuite-virtual-category/etc/elasticsuite_search_request.xml

essentially cleanup of collection filtering in autocomplete since it's now handled by default container filters.
Also refactored the filter names in camel case.

Context filters cleaning

---

src/module-elasticsuite-catalog/Plugin/CatalogSearch/ResultPlugin.php

Prevent applying the redirect on one result if another exists

---

src/module-elasticsuite-catalog/etc/elasticsuite_indices.xml
src/module-elasticsuite-core/Search/Adapter/Elasticsuite/Spellchecker.php
src/module-elasticsuite-core/Search/Request/Query/Fulltext/QueryBuilder.php
src/module-elasticsuite-core/etc/elasticsuite_analysis.xml

Partial sku search

---

src/module-elasticsuite-catalog/Model/ResourceModel/Product/Indexer/Fulltext/Datasource/AttributeData.php

Fix #808 by enforcing status attribute to be indexed.

Enforce indexation of status attribute for products.

---

src/module-elasticsuite-catalog/Block/Navigation/Renderer/Slider.php
src/module-elasticsuite-catalog/Model/Layer/Filter/DataProvider/Decimal.php
src/module-elasticsuite-catalog/Model/Layer/Filter/Decimal.php

Fix usage of negative values in the decimal slider.

---

src/module-elasticsuite-catalog/Block/Navigation.php

Ensure retrieving page layout if overridden in XML layout file.

---

src/module-elasticsuite-core/etc/di.xml

Adding environment specific and sensitive configuration params.

---

src/module-elasticsuite-catalog/view/adminhtml/web/js/form/element/product-sorter.js
src/module-elasticsuite-virtual-category/view/adminhtml/ui_component/category_form.xml

Prevent category facet config to be submitted on category preview

---

src/module-elasticsuite-tracker/Model/EventIndex.php
src/module-elasticsuite-tracker/Model/IndexResolver.php
src/module-elasticsuite-tracker/Model/SessionIndex.php

Fix log ingest error when a store view is deleted.

---

src/module-elasticsuite-virtual-category/Model/Category/Attribute/Source/VirtualCategoryRoot/CollectionFactory.php

This is the complementary point of #887 .
Regards

Prevent assigning a cross-tree virtual category root.

---

src/module-elasticsuite-tracker/etc/elasticsuite_indices.xml
src/module-elasticsuite-tracker/view/frontend/web/js/tracking.js

* Fix resolution var name
* Append GA campaign tracking to the mapping
* Fix SKU analyzer
* Make search query sortable

Tracking indexing fine tuning

---

src/module-elasticsuite-catalog-optimizer/Api/Data/OptimizerInterface.php
src/module-elasticsuite-catalog-optimizer/Model/Optimizer.php
src/module-elasticsuite-catalog-optimizer/Model/Optimizer/Limitation/ReadHandler.php
src/module-elasticsuite-catalog-optimizer/Model/Optimizer/Limitation/SaveHandler.php
src/module-elasticsuite-catalog-optimizer/Model/Optimizer/Locator/LocatorInterface.php
src/module-elasticsuite-catalog-optimizer/Model/Optimizer/Locator/RegistryLocator.php
src/module-elasticsuite-catalog-optimizer/Model/ResourceModel/Optimizer.php
src/module-elasticsuite-catalog-optimizer/Model/ResourceModel/Optimizer/Limitation.php
src/module-elasticsuite-catalog-optimizer/Setup/OptimizerSetup.php
src/module-elasticsuite-catalog-optimizer/Setup/UpgradeSchema.php
src/module-elasticsuite-catalog-optimizer/Ui/Component/Optimizer/Form/DataProvider.php
src/module-elasticsuite-catalog-optimizer/Ui/Component/Optimizer/Form/Modifier/Limitation.php
src/module-elasticsuite-catalog-optimizer/Ui/Component/Optimizer/Form/Modifier/Preview.php
src/module-elasticsuite-catalog-optimizer/Ui/Component/Optimizer/Form/Modifier/SearchTerms.php
src/module-elasticsuite-catalog-optimizer/etc/adminhtml/di.xml
src/module-elasticsuite-catalog-optimizer/etc/di.xml
src/module-elasticsuite-catalog-optimizer/etc/module.xml

- Creating new tables to store optimizer and categories/queries associations.
- Save/Read handler to save/load these links.
- Refactoring of Optimizer Ui component to separate the different modifiers (Preview part, conditional optimizer part).

Feature conditional optimizer backend

---

src/module-elasticsuite-core/etc/elasticsuite_analysis.xml

Change the default tokenizer to standard instead of whitespace.

---

src/module-elasticsuite-core/Search/Request/ContainerConfiguration/RelevanceConfig.php

Properly check if phonetic search is enabled.

---

src/module-elasticsuite-catalog/Model/Layer/Filter/Attribute.php

Remove facets when all options are the same for each products.

---

src/module-elasticsuite-virtual-category/etc/mview.xml

Replace #1076 by rebasing it on 2.6.x branch.
Fix #947

Fix category position index

---

src/module-elasticsuite-catalog-optimizer/Model/ResourceModel/Optimizer/Limitation.php

Fix optimizer appliance.

---

src/module-elasticsuite-catalog-optimizer/view/adminhtml/layout/smile_elasticsuite_catalog_optimizer_optimizer_edit.xml

Remove store switcher for optimizer edit form.

---

src/module-elasticsuite-catalog/Model/Layer/Filter/Decimal.php
src/module-elasticsuite-catalog/Model/Layer/Filter/DecimalFilterTrait.php
src/module-elasticsuite-catalog/Model/Layer/Filter/Price.php

Fix #1096 
@nicobatty can you test this one and give me your feedback ?

Add nested filter on customer group id for price filter.

---

src/module-elasticsuite-catalog/etc/elasticsuite_indices.xml

Fix typo in XML comment

---

src/module-elasticsuite-thesaurus/Model/Index.php

Fixes #1089, fixes #1123 multibyte UTF8 chars in

---

src/module-elasticsuite-catalog/view/frontend/web/css/source/_module.less

fix styles to fit more with M2 variables/syntax

fix styles

---

src/module-elasticsuite-tracker/Cron/IndexLogEvent.php
src/module-elasticsuite-tracker/Model/ResourceModel/EventQueue.php

of 10K events at each cronjob run.

Resolves #1110 tracker log events indexed by chunk

---

src/module-elasticsuite-core/Indexer/GenericIndexerHandler.php

Add dimensions with dummy default value for indexer interface.

---

src/module-elasticsuite-catalog/view/frontend/web/js/attribute-filter.js

[Facet Search] Fixed bug in IE because of unsupported .includes #1102

---

src/module-elasticsuite-catalog/Model/Product/Indexer/Fulltext/Datasource/AttributeData.php

Fix missing assignment

---

src/module-elasticsuite-thesaurus/Model/Index.php

Fix the case when analysis tokens are missing.

---

src/module-elasticsuite-catalog/Model/Layer/Category/FilterableAttributeList.php
src/module-elasticsuite-catalog/Plugin/Ui/Category/Form/DataProviderPlugin.php

of layered navigation filterable attributes
Required after PR #1164 (see issue #1153)

Fixes #1192 Homogeneous secondary sort order

---

src/module-elasticsuite-catalog/Model/Product/Indexer/Fulltext/Datasource/AttributeData.php

Prevent null valued attributes being added to indexed_attributes field

---

composer.json
src/module-elasticsuite-catalog/etc/module.xml

Fixes #1222 Explicit composer/module dependencies

---

src/module-elasticsuite-core/Model/Search/RequestMapper.php

Fix filter mapping for fields with multiple condition_type

---

src/module-elasticsuite-catalog/Model/Category/Indexer/Fulltext/Datasource/AttributeData.php

See Smile-SA/elasticsuite#1236 for details.

Fixes issue 1236 Category index not working

---

src/module-elasticsuite-tracker/Plugin/QuotePlugin.php

Change addtocart plugin to an after plugin.

---

src/module-elasticsuite-tracker/Model/SessionIndex.php

Ensure tracking event store_id is properly set before using it.

---

src/module-elasticsuite-virtual-category/Model/ResourceModel/Product/Indexer/Fulltext/Changelog/Writer.php
src/module-elasticsuite-virtual-category/Plugin/Catalog/Category/ReindexOnUpdateStorePositions.php
src/module-elasticsuite-virtual-category/etc/di.xml

after a reset of positions and blacklist

Force scheduled reindexing of affected products

---

src/module-elasticsuite-catalog/view/adminhtml/templates/catalog/product/attribute/js.phtml
src/module-elasticsuite-swatches/Model/Serialize/Serializer/FormData.php
src/module-elasticsuite-swatches/Plugin/Catalog/Controller/Adminhtml/Product/Attribute/SavePlugin.php
src/module-elasticsuite-swatches/Plugin/Catalog/Controller/Adminhtml/Product/Attribute/ValidatePlugin.php
src/module-elasticsuite-swatches/etc/adminhtml/di.xml
src/module-elasticsuite-swatches/view/adminhtml/web/js/product-attributes.js

Backported changes in native JS code (catalog and swatches handling).
Removed the indentation of catalog/product/attribute/js.phtml for easier comparison.

Fixes #1248 Dropdown attributes values not saved

---

src/module-elasticsuite-catalog/Model/Autocomplete/Product/AttributeConfig.php

incorrectly displayed with a price range

Fixes #1250 Fixed price bundle in autocomplete

---

src/module-elasticsuite-catalog/Model/Autocomplete/Product/AttributeConfig.php

incorrectly displayed with a price range

Fixes #1250 Fixed price bundle in autocomplete (M2 2.3.x)

---

src/module-elasticsuite-catalog-optimizer/Ui/Component/Optimizer/Form/Modifier/Preview.php
src/module-elasticsuite-catalog-optimizer/view/adminhtml/ui_component/smile_elasticsuite_catalog_optimizer_form.xml
src/module-elasticsuite-catalog-optimizer/view/adminhtml/web/js/components/form/optimizer/optimizer-preview-type.js

Fix #1309 
To be merged on 2.6.x and cascaded.

Fix optimizer preview

---

src/module-elasticsuite-catalog-optimizer/Model/ResourceModel/Optimizer/Config/Attributes/Collection.php
src/module-elasticsuite-catalog-rule/Model/Rule/Condition/Product.php
src/module-elasticsuite-catalog-rule/Model/Rule/Condition/Product/AttributeList.php

To be merged in 2.6.x and cascaded
Fix #1307 
Fix #1311 
Fix #1312 
Fix #1239

Fix attributes rules

---

src/module-elasticsuite-catalog-optimizer/Model/Optimizer/Preview.php

Fixes #1308 Optimizer category preview not working

---

src/module-elasticsuite-catalog-optimizer/Model/Optimizer/Preview.php

Fixes #1308 Optimizer category preview not working (M2 2.3.x)

---

src/module-elasticsuite-catalog/Model/ResourceModel/Product/Fulltext/Collection.php

Revamp of PR #1328 to address the phpmd issue.
(See possible origin/fix : https://github.com/phpmd/phpmd/issues/409 and https://github.com/phpmd/phpmd/pull/495)

Feature allow resetting sort order 2.6.x

---

src/module-elasticsuite-catalog/Model/ResourceModel/Product/Fulltext/Collection.php

M2 2.3.x/ElasticSuite 2.7.x version of #1331 / #1328

Allow resetting the sort order to an empty array (2.7.x)

---

src/module-elasticsuite-catalog/Plugin/Ui/Category/Form/DataProviderPlugin.php

Will aggregate commits related to Fix #1244

WIP : Admin category loading optimization

---

src/module-elasticsuite-tracker/view/frontend/templates/config.phtml
src/module-elasticsuite-tracker/view/frontend/templates/variables/page.phtml

by browser plugin (ex: ublock origin)

Fixes #1321 Prevent js errors if tracker blocked (2.7.x)

---

src/module-elasticsuite-swatches/Model/Plugin/ProductImage.php

2.7.x / M2 2.3.x version of PR #1290

Fix swatches image 2.7.x

---

composer.json
src/module-elasticsuite-catalog/Model/Layer/Filter/Decimal.php
src/module-elasticsuite-core/Api/Client/ClientInterface.php
src/module-elasticsuite-core/Model/Search/Request/RelevanceConfig.php
src/module-elasticsuite-core/Search/Context.php
src/module-elasticsuite-core/Search/Request/ContainerConfiguration/RelevanceConfig.php
src/module-elasticsuite-core/Search/Request/ContainerConfiguration/RelevanceConfig/FuzzinessConfig.php
src/module-elasticsuite-thesaurus/Block/Adminhtml/Thesaurus/Renderer/AbstractRenderer.php
src/module-elasticsuite-thesaurus/Block/Adminhtml/Thesaurus/Renderer/Synonyms.php

Update quality suite version.

---

src/module-elasticsuite-catalog/Model/Category/Filter/Provider.php
src/module-elasticsuite-catalog/Plugin/Ui/Category/Form/DataProviderPlugin.php
src/module-elasticsuite-virtual-category/Block/Adminhtml/Catalog/Category/VirtualRule.php
src/module-elasticsuite-virtual-category/Model/Category/Attribute/VirtualRule/ReadHandler.php
src/module-elasticsuite-virtual-category/Model/Category/Filter/Provider.php
src/module-elasticsuite-virtual-category/etc/di.xml

Fix category admin ui

---

src/module-elasticsuite-swatches/view/frontend/layout/catalogsearch_result_index.xml

Remove not existing anymore swatches css file.

---

src/module-elasticsuite-core/Search/Request/RelevanceConfig/App/Config/ScopeCodeResolver.php
src/module-elasticsuite-core/Search/Request/RelevanceConfig/App/Config/ScopePool.php

Please review this PR. 
Should be BC since it's a completely new class, but who knows ...
Fix #1361

Fix scope configuration bug on Magento 2.2.8

---

composer.json

Fixes #1363 in 2.7.x (for M2 2.3.1)

Fixes #1363 Allow elasticsearch/elasticsearch 6.1

---

src/module-elasticsuite-core/Search/Request/RelevanceConfig/App/Config/ScopeCodeResolver.php
src/module-elasticsuite-core/Search/Request/RelevanceConfig/App/Config/ScopePool.php

Prevent #1361 on future versions of M2 2.3.x as the original commit (https://github.com/magento/magento2/pull/16940) might still be forward ported from 2.2.x to 2.3.x (see https://github.com/magento/magento2/pull/21633)

Prevent Magento 2.2.8 scope configuration bug in future 2.3.x releases

---

src/module-elasticsuite-swatches/Block/Navigation/Renderer/Swatches/RenderLayered.php

Fix text swatches comparaison.

---

src/module-elasticsuite-catalog/Plugin/Ui/Category/Form/DataProviderPlugin.php

Fix proper restriction level for layered navigation filters setting.

---

src/module-elasticsuite-catalog-rule/Api/Data/ConditionInterface.php
src/module-elasticsuite-catalog-rule/Model/Data/Condition.php
src/module-elasticsuite-catalog-rule/Model/Rule.php
src/module-elasticsuite-catalog-rule/etc/di.xml
src/module-elasticsuite-virtual-category/Api/Data/VirtualRuleInterface.php
src/module-elasticsuite-virtual-category/Model/Rule.php
src/module-elasticsuite-virtual-category/Model/Webapi/TypeLocator/VirtualCategoryLocator.php
src/module-elasticsuite-virtual-category/etc/di.xml

Fix virtual category api

---

src/module-elasticsuite-virtual-category/Setup/UpgradeData.php
src/module-elasticsuite-virtual-category/Setup/VirtualCategorySetup.php
src/module-elasticsuite-virtual-category/etc/module.xml

Fixes #1369 virtual_category_root new default value 2.3.x

---

src/module-elasticsuite-virtual-category/Setup/UpgradeData.php
src/module-elasticsuite-virtual-category/Setup/VirtualCategorySetup.php
src/module-elasticsuite-virtual-category/etc/module.xml

Fixes #1369 virtual_category_root new default value 2.2.x

---

src/module-elasticsuite-catalog/etc/elasticsuite_indices.xml

Set SKU field as filterable by default.

---

src/module-elasticsuite-catalog/view/frontend/web/js/attribute-filter.js

fix for https://github.com/Smile-SA/elasticsuite/issues/1424

add missing semicolon

---

src/module-elasticsuite-virtual-category/Model/Rule.php
src/module-elasticsuite-virtual-category/Model/Rule/Condition/Combine.php
src/module-elasticsuite-virtual-category/Model/Rule/Condition/Product.php

fix for https://github.com/Smile-SA/elasticsuite/issues/1420

fix condition "category is not one of category ids list"

---

src/module-elasticsuite-catalog/Plugin/LayerPlugin.php
src/module-elasticsuite-catalog/etc/di.xml
src/module-elasticsuite-catalog/etc/module.xml

Fix layered navigation with Magento 2.3.2

---

src/module-elasticsuite-catalog-optimizer/Model/Optimizer/Functions/CacheKeyProvider.php
src/module-elasticsuite-catalog-optimizer/view/adminhtml/ui_component/smile_elasticsuite_catalog_optimizer_form.xml

and removal of a useless requirement

Adding sort orders on optimizers edit form fieldsets

---

src/module-elasticsuite-catalog/view/adminhtml/web/js/category/filter-config/record.js

Fixes #1612 Prevent already pinned attr order loss

---

src/module-elasticsuite-catalog/view/adminhtml/templates/catalog/product/attribute/js.phtml

Hi :smile: ,
~I stumbled upon the error this morning and although I noticed [this PR](https://github.com/Smile-SA/elasticsuite/pull/1405), the fix seems to be official now and is a bit different.~
> Since our file is a copy-paste of the legacy one 
As I read this again, might be time for a full copy-paste again. Here is the force-push!
Thanks for this awesome module!

Backport attributes administration script from upstream

---

src/module-elasticsuite-catalog-optimizer/view/adminhtml/ui_component/smile_elasticsuite_catalog_optimizer_form.xml

for attribute based search optimizers

Fixes #1635 log1p instead of log for logarithmic fn

---

src/module-elasticsuite-catalog/Block/Navigation.php

Fixes #1656 Allows 0 expanded facets
See https://github.com/Smile-SA/elasticsuite/issues/1656 for more information

#1656 Allows 0 expanded facets

---

src/module-elasticsuite-catalog/Model/ProductSorter/AbstractPreview.php
src/module-elasticsuite-catalog/Model/Search/Preview.php

by providing the correct search request name to the collection/collection factory.

Fixes #1659 Search optimizers applied on search terms preview

---

src/module-elasticsuite-catalog/Plugin/Search/RequestMapperPlugin.php

handling when applying sort orders in a quick_search_container request context.

Fixes #1723 REST v1/search unknown/new search query

---

src/module-elasticsuite-catalog/Plugin/Ui/Category/Form/DataProviderPlugin.php

Fixes the "Attention Something went wrong." error 
(in the production mode, you will get a redirect to the homepage), if you try to 
schedule new update on the default category. (Catalog -> Categories)
Also fixes the error if you try to schedule new update on the default category
on a product.

Fixes #1741 Schedule new Update error

---

src/module-elasticsuite-catalog/Model/Layer/Filter/Attribute.php

Fixes #1703 remove htmlspecialchars

---

src/module-elasticsuite-core/etc/elasticsuite_analysis.xml

either to fix or customise stemmer output.

Resolves #1742 Per language stemmer override feature

---

src/module-elasticsuite-core/Index/Analysis/Config/Converter.php
src/module-elasticsuite-core/etc/elasticsuite_analysis.xsd

add ElasticSearch "normalizers" support (https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-normalizers.html)
Example usage in `etc/elasticsuite_analysis.xml`
```xml
<?xml version="1.0"?>
<analysis xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="urn:magento:module:Smile_ElasticsuiteCore:etc/elasticsuite_analysis.xsd">
<normalizers>
<normalizer name="custom_lowercase" type="custom" language="default">
<char_filters></char_filters>
<filters>
<filter ref="lowercase" />
</filters>
</normalizer>
</normalizers>
<filters>
<filter name="reference_ngram_custom" type="edge_ngram" language="default">
<min_gram>3</min_gram>
<max_gram>20</max_gram>
<token_chars></token_chars>
</filter>
</filters>
<analyzers>
<analyzer …
```

add ElasticSearch "normalizers" support

---

.travis.yml
Resources/tests/graphql/category/query.gql
Resources/tests/graphql/category/variables.json
Resources/tests/graphql/productdetail/query.gql
Resources/tests/graphql/productdetail/variables.json
Resources/tests/graphql/search/query.gql
Resources/tests/graphql/search/variables.json
Resources/travis/apache.conf
Resources/travis/deployVeniaSampleData.sh
Resources/travis/prepare_apache.sh
Resources/travis/prepare_graphql.sh
Resources/travis/test_data.sh
Resources/travis/test_graphql.sh
Resources/travis/test_magento.sh
Resources/travis/test_web.sh

Adding Venia sample data to be able to proceed with : 
- HTTP test for homepage, autocomplete and search
- GraphQL query for search, category and product detail

Add Venia sample data to the build and more tests

---

src/module-elasticsuite-catalog/Model/ResourceModel/Product/Fulltext/Collection.php
src/module-elasticsuite-catalog/Model/ResourceModel/Product/Fulltext/Collection/SearchResultApplier.php

Pull request to fix issue described in #1823

#1823 Fix issue with raw queries being escaped with backticks

---

src/module-elasticsuite-catalog-optimizer/Model/Optimizer/Preview/Item.php
src/module-elasticsuite-catalog/Model/Layer/Filter/Price.php
src/module-elasticsuite-catalog/Model/ProductSorter/ItemDataFactory.php

Fixes error using incorrect variable for calculate price
Added required parameter for method _renderRangeLabel

Fixes error using incorrect variable for calculate price and added required parameter for method _renderRangeLabel

---

src/module-elasticsuite-catalog-graph-ql/Model/Resolver/Products.php
src/module-elasticsuite-catalog-graph-ql/Model/Resolver/Products/Query/Search.php
src/module-elasticsuite-catalog-optimizer/Ui/Component/Listing/Column/OptimizerActions.php
src/module-elasticsuite-catalog-optimizer/i18n/de_DE.csv
src/module-elasticsuite-catalog-optimizer/i18n/en_US.csv
src/module-elasticsuite-catalog-optimizer/i18n/fr_FR.csv

Fixed confirm message for delete optimizer
Added required parameter for method getResult in GraphQl module

Fixed confirm message for delete optimizer and added required parameter for method getResult in GraphQl module

---

src/module-elasticsuite-indices/Model/IndexStatsProvider.php

Fix #1865 index size

---

src/module-elasticsuite-catalog/Model/ResourceModel/Product/Fulltext/Collection.php

This pull request reintroduces change from already merged https://github.com/Smile-SA/elasticsuite/pull/370, which was overwritten during refactor: https://github.com/Smile-SA/elasticsuite/commit/30a8d87abc1f69bdbc5046a26a6926f109dd12cd#diff-6a285666f9fbbc83496890ef4c186174R482 
Original issue: https://github.com/Smile-SA/elasticsuite/issues/280

Fix pagination when changing "product per page" on last page

---

src/module-elasticsuite-catalog/Model/Product/Indexer/Fulltext/Datasource/PriceData.php

Fix #1861 explicit cast of price as float

---

src/module-elasticsuite-virtual-category/Plugin/Search/RequestMapperPlugin.php

Fix #1866 Multiple categories filter

---

src/module-elasticsuite-catalog/Model/Layer/Filter/Attribute.php

Not needed anymore to prevent XSS since 2.3.3

Fixes #1978 Remove extra escaping preventing filter removal

---

src/module-elasticsuite-catalog/Model/Layer/Filter/Attribute.php
src/module-elasticsuite-catalog/Model/Layer/Filter/Item/Attribute.php

current filter item value and applied values.

Fixes #1978 Do not rely on escaped value to compare

---

src/module-elasticsuite-catalog-rule/Api/Rule/Condition/Product/SpecialAttributeInterface.php
src/module-elasticsuite-catalog-rule/Model/Rule/Condition/Product.php
src/module-elasticsuite-catalog-rule/Model/Rule/Condition/Product/QueryBuilder.php
src/module-elasticsuite-catalog-rule/Model/Rule/Condition/Product/SpecialAttribute/HasImage.php
src/module-elasticsuite-catalog-rule/Model/Rule/Condition/Product/SpecialAttribute/IsDiscount.php
src/module-elasticsuite-catalog-rule/Model/Rule/Condition/Product/SpecialAttribute/IsInStock.php

Allows to have operators and values for special attributes.
Allows building a custom search query using those operator and values.

Catalog rules special attr. interface update

---

src/module-elasticsuite-core/Search/Request/ContainerConfiguration/BaseConfig/Reader.php

in elasticsearch_search_request.xml

Allow defining sub-aggregations accross modules (2.8.x)

---

src/module-elasticsuite-core/Search/Request/ContainerConfiguration/BaseConfig/Reader.php

in elasticsearch_search_request.xml

Allow defining sub-aggregations accross modules (2.9.x)

---

src/module-elasticsuite-core/Plugin/Setup/SearchConfigOptionsListPlugin.php
src/module-elasticsuite-core/Setup/ConfigOptionsList.php
src/module-elasticsuite-core/Setup/InstallConfig.php
src/module-elasticsuite-core/Setup/Validator.php
src/module-elasticsuite-core/etc/di.xml

Allow installing with standard Magento Elasticsearch parameters

---

src/module-elasticsuite-thesaurus/Model/Index.php
src/module-elasticsuite-thesaurus/Plugin/QueryRewrite.php

[Thesaurus] - Use main query boost to calculate rewrite query boost

---

src/module-elasticsuite-virtual-category/Plugin/Staging/Catalog/Category/DataProviderPlugin.php
src/module-elasticsuite-virtual-category/etc/adminhtml/di.xml

Remove assign_products and facet_config from staging category form

---

src/module-elasticsuite-core/Api/Client/ClientInterface.php
src/module-elasticsuite-core/Api/Index/IndexOperationInterface.php
src/module-elasticsuite-core/Client/Client.php
src/module-elasticsuite-core/Index/IndexOperation.php
src/module-elasticsuite-tracker/Api/DateBoundsInterface.php
src/module-elasticsuite-tracker/Model/EventIndex.php
src/module-elasticsuite-tracker/Model/EventIndex/DateBounds.php
src/module-elasticsuite-tracker/Model/IndexManager.php
src/module-elasticsuite-tracker/Model/IndexResolver.php
src/module-elasticsuite-tracker/Model/ResourceModel/EventIndex/DateBounds.php
src/module-elasticsuite-tracker/Model/SessionIndex.php
src/module-elasticsuite-tracker/Setup/TrackerSetup.php
src/module-elasticsuite-tracker/Setup/UpgradeData.php
src/module-elasticsuite-tracker/etc/adminhtml/system.xml
src/module-elasticsuite-tracker/etc/config.xml
src/module-elasticsuite-tracker/etc/module.xml
src/module-elasticsuite-tracker/i18n/en_US.csv
src/module-elasticsuite-tracker/i18n/fr_FR.csv

* Change the way tracking indices are created to monthly
* Refactor tracking indices purge mechanism
* Wrap existing tracking indices into monthly indices

Change tracking indices from daily to monthly

---

src/module-elasticsuite-catalog/Helper/AbstractAttribute.php

Do not reload attributes in layered navigation 

---

.github/workflows/20-integration.yml
src/module-elasticsuite-catalog/view/frontend/requirejs-config.js

Add shim for jquery/ui

---

src/module-elasticsuite-catalog/Model/Product/Indexer/Fulltext/Datasource/CategoryData.php
src/module-elasticsuite-catalog/Model/Search/Request/Field/Mapper.php
src/module-elasticsuite-catalog/etc/elasticsuite_indices.xml

Reverts Smile-SA/elasticsuite#2326

Revert "Update category_uid attribute mapping"

---

src/module-elasticsuite-catalog/Block/Plugin/Adminhtml/Product/Attribute/Edit/Tab/FrontPlugin.php

ESP-309, ESP-310 REFACTOR: around plugins should be avoided at any price + fix documentation

---

src/module-elasticsuite-catalog-optimizer/view/adminhtml/ui_component/smile_elasticsuite_catalog_optimizer_form.xml
src/module-elasticsuite-catalog-optimizer/view/adminhtml/web/js/components/form/optimizer/constant_score/slider.js
src/module-elasticsuite-core/i18n/en_US.csv
src/module-elasticsuite-core/i18n/fr_FR.csv
src/module-elasticsuite-core/view/base/requirejs-config.js
src/module-elasticsuite-core/view/base/web/js/validation/validator-mixin.js

* Constant score  was not saved in DB when the value was set only via the slider

 [Optimizer] Fix bug on constant score slider

---

src/module-elasticsuite-catalog-rule/Model/Rule/Condition/Product/SpecialAttribute/IsDiscount.php
src/module-elasticsuite-catalog-rule/etc/di.xml
src/module-elasticsuite-virtual-category/Helper/Rule.php
src/module-elasticsuite-virtual-category/etc/di.xml

by adding support for current customer group.

Fixes #2380 is_discount tiers price support (2.8.x)

---

src/module-elasticsuite-catalog-rule/Model/Rule/Condition/Product/SpecialAttribute/IsDiscount.php
src/module-elasticsuite-catalog-rule/etc/di.xml
src/module-elasticsuite-virtual-category/Helper/Rule.php
src/module-elasticsuite-virtual-category/etc/di.xml

by adding support for current customer group.

Fixes #2380 is_discount tiers price support

---

src/module-elasticsuite-core/Client/Client.php

Stops calling code in the constructor of the Client class, but defers it to when it's actually needed.
We ran into an obscure problem where we have a Magento codebase with this module installed, and have a bunch of configuration settings in the `app/etc/config.php` file (including theme and store definitions) and an empty `app/etc/env.php` file and an empty database.
When we then called `bin/magento setup:install --no-interaction --cleanup-database ...` it gave us two issues:
1. Somewhere at the beginning of the command, this was outputted (it didn't stop, but I don't like to see such errors):
```
...
[Progress: 4 / 990]
Cleaning up database...
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'magento2.theme' doesn't exist, query was: SELECT `main_table`.* FROM `theme` AS …
```

Don't execute code in the constructor of the Client class

---

src/module-elasticsuite-catalog/view/adminhtml/web/template/form/element/product-sorter.html
src/module-elasticsuite-catalog/view/frontend/web/template/attribute-filter.html
src/module-elasticsuite-catalog/view/frontend/web/template/autocomplete/category.html
src/module-elasticsuite-catalog/view/frontend/web/template/autocomplete/product-attribute.html
src/module-elasticsuite-catalog/view/frontend/web/template/autocomplete/product.html

By using correct escaping/binding methods of underscore (frontend) and knockoutjs (backend)

Fixes #2590 Possible XSS issues from contributed data

---

src/module-elasticsuite-core/view/frontend/templates/search/form.mini.phtml

Also rughly cleaned up the template 😉

Made the searchbar instantiatable multiple times

---

src/module-elasticsuite-core/view/frontend/templates/search/form.mini.phtml

* Generate an id also for the input field and use it to link label and input again

Fix #2668 Mobile search bar is not opening on click

---

.github/workflows/20-integration.yml

to 2.17.0 which no longer supports PHP 7.3 and PHP 7.4

Fixes #2687 Prevent laminas/laminas-mail upgrade

---

src/module-elasticsuite-catalog-graph-ql/Model/Resolver/Products/ContextUpdater.php
src/module-elasticsuite-virtual-category/Plugin/Search/RequestMapperPlugin.php

Fixes #2760 by adding some defensive isset() checks on the array keys being accessed.

Added some isset checks for array keys being used in GraphQl

---

src/module-elasticsuite-indices/Model/IndexStatusProvider.php

See https://github.com/Smile-SA/elasticsuite/issues/2778

Fix exception on PHP 8.1

---

src/module-elasticsuite-catalog/Model/Product/Indexer/Fulltext/Datasource/AttributeData.php
src/module-elasticsuite-catalog/etc/adminhtml/system.xml
src/module-elasticsuite-catalog/etc/config.xml

Probably need to add text translation for a new setting in Magento BO, at least for French.

#2733, Fix indexing of child products SKUs

---

src/module-elasticsuite-virtual-category/Controller/Router.php

Fix issue #2856: Pagination, sorting and limit on virtual category tree

---

src/module-elasticsuite-virtual-category/Model/VirtualCategory/Root.php

This PR fixes https://github.com/Smile-SA/elasticsuite/issues/2829

[Virtual Category] Unset virtual category root before setting it #1203860 #2829

---

src/module-elasticsuite-indices/etc/config.xml

Set proper key for catalogsearch_fulltext index.

---

src/module-elasticsuite-indices/Model/IndexStatusProvider.php
src/module-elasticsuite-indices/Model/ResourceModel/WorkingIndexer/Collection.php

Fix #2835 remanent issue (datetime)

Fixing Datetime issues

---

src/module-elasticsuite-catalog/etc/frontend/di.xml

Remove erratic plugin of Magento_InventoryCatalog

---

src/module-elasticsuite-virtual-category/Observer/AddCategoryAttributesToSelect.php
src/module-elasticsuite-virtual-category/etc/events.xml

This will make sure that 'Virtual Categories' will correctly process product loading

Add observer to load mandatory attributes on category collections

---

src/module-elasticsuite-catalog/etc/frontend/di.xml

In sync with MSI 1.2.6, remove undeclared plugin

---

src/module-elasticsuite-core/Model/ResourceModel/Search/Request/RelevanceConfig.php

Adding missing parameter into constructor

---

src/module-elasticsuite-catalog-graph-ql/DataProvider/Product/SearchCriteriaBuilder.php

See https://github.com/magento/magento2/commit/7ab48b08dc6cda2853c95033e44152fa98f89258

Change !empty check to isset

---

src/module-elasticsuite-catalog-graph-ql/DataProvider/Product/SearchCriteriaBuilder.php

Reverts Smile-SA/elasticsuite#3183

Revert "Change !empty check to isset"

---

src/module-elasticsuite-core/Search/Request/Query/Fulltext/QueryBuilder.php

Probably a prequel to a different way to deal with span matching.

Use case insensitive query for span matching.

---

src/module-elasticsuite-catalog/Model/Category/Attribute/Source/SortDirection.php
src/module-elasticsuite-catalog/Plugin/Catalog/Ui/DataProvider/Product/Form/Modifier/HideProductAttributesPlugin.php
src/module-elasticsuite-catalog/Plugin/Category/Toolbar/SortDirectionPerCategoryPlugin.php
src/module-elasticsuite-catalog/Setup/CatalogSetup.php
src/module-elasticsuite-catalog/Setup/UpgradeData.php
src/module-elasticsuite-catalog/etc/di.xml
src/module-elasticsuite-catalog/etc/module.xml
src/module-elasticsuite-catalog/view/adminhtml/ui_component/category_form.xml
src/module-elasticsuite-catalog/view/adminhtml/web/js/form/element/product-sorter.js
src/module-elasticsuite-catalog/view/adminhtml/web/js/form/element/product-sorter/item.js
src/module-elasticsuite-catalog/view/adminhtml/web/template/form/element/product-sorter.html
src/module-elasticsuite-virtual-category/Model/Preview.php
src/module-elasticsuite-virtual-category/view/adminhtml/ui_component/category_form.xml

Sort direction per category 2.10 feature

---

src/module-elasticsuite-core/Model/DataProvider/Suggestions.php

[Suggestions] Respect search configuration

---

src/module-elasticsuite-thesaurus/Model/Index.php

[Thesaurus] Fix dashes in synonyms

---

src/module-elasticsuite-virtual-category/Helper/Config.php
src/module-elasticsuite-virtual-category/Model/Rule.php
src/module-elasticsuite-virtual-category/etc/adminhtml/system.xml
src/module-elasticsuite-virtual-category/etc/config.xml
src/module-elasticsuite-virtual-category/i18n/en_US.csv
src/module-elasticsuite-virtual-category/i18n/fr_FR.csv

[VirtualCategories] Option to force empty category if virtual category root disabled

---

src/module-elasticsuite-catalog-optimizer/Controller/Adminhtml/Optimizer/Preview.php

[Optimizers] Fallback to root category for category preview

---

src/module-elasticsuite-catalog-optimizer/Controller/Adminhtml/Optimizer/Preview.php
src/module-elasticsuite-catalog-optimizer/Model/Optimizer/Preview.php
src/module-elasticsuite-catalog-optimizer/etc/adminhtml/di.xml

which support category limitations

[CatalogOptimizer] Category preview for third party containers

---

src/module-elasticsuite-indices/Model/IndexStatsProvider.php

Default status was 'rebuilding' which was confusing.

[Indices] Status 'unknown' when stats fails + logging failures

---

src/module-elasticsuite-catalog/etc/db_schema.xml

add column type in db_schema.xml, required from magento 2.4.8-beta1

---

src/module-elasticsuite-catalog-graph-ql/DataProvider/Product/LayeredNavigation/Builder/Attribute.php

Added default label for attribute when frontendlabels are empty

Added default attribute label

---

src/module-elasticsuite-core/Search/Request/Builder.php

in the source document.
Not supported by the request mapper yet.

[Core] Introduce ability to include/exclude fields

---

src/module-elasticsuite-core/Search/Adapter/Elasticsuite/Request/Mapper.php
src/module-elasticsuite-core/Search/Request.php
src/module-elasticsuite-core/Search/Request/Builder.php
src/module-elasticsuite-core/Search/RequestInterface.php

and adding support in the request mapper.

[Core] include/exclude fields outside request builder

---

src/module-elasticsuite-catalog/Model/CategoryPermissions/Filter/Provider.php
src/module-elasticsuite-catalog/Model/Product/Indexer/Fulltext/Datasource/CategoryPermissions.php
src/module-elasticsuite-catalog/Model/Product/Search/Request/Container/Filter/CategoryPermissions.php
src/module-elasticsuite-catalog/Plugin/Search/RequestMapperPlugin.php
src/module-elasticsuite-catalog/etc/di.xml
src/module-elasticsuite-catalog/etc/elasticsuite_indices.xml
src/module-elasticsuite-catalog/etc/elasticsuite_search_request.xml

Fixes #2861 
Rebased version of #3541

[Catalog] Implementing Category permissions

---

src/module-elasticsuite-indices/Console/Command/PurgeGhostIndices.php
src/module-elasticsuite-indices/Controller/Adminhtml/Index/RemoveGhostIndices.php
src/module-elasticsuite-indices/Model/GhostIndexPurger.php
src/module-elasticsuite-indices/etc/di.xml

+ fixed DI (use of proxy)
+ renamed command as elasticsuite:indices:purgeghosts

[Indices] Feature #3624, add a cli command to remove all ghost indices

---

src/module-elasticsuite-tracker/view/frontend/layout/cms_page_view.xml

Update referenceContainer for CMS tracker (2.10.x)

---

src/module-elasticsuite-core/Index/Bulk/BulkResponse.php

those lines are already removed in 2.11.x

[Core] Anticipate doc type removal in later ES/OS versions

---

src/module-elasticsuite-catalog/view/frontend/templates/layer/filter/attribute.phtml
src/module-elasticsuite-catalog/view/frontend/web/js/slider.js
src/module-elasticsuite-catalog/view/frontend/web/template/attribute-filter.html

Adjustments:
- 'Show more / less' buttons are accessible via keyboard
- Added missing 'aria-label' attribute to the search input & range slider handles
- SR can see the 'no results' message now

feat: Catalog - accessibility adjustments

---

src/module-elasticsuite-catalog/Plugin/Layer/CategoryPlugin.php
src/module-elasticsuite-virtual-category/Observer/ManageVirtualCategoryWithSubtree.php
src/module-elasticsuite-virtual-category/etc/frontend/events.xml

When "category_filter_use_url_rewrites" is set to false

[Layer] Fix category in search context

---

src/module-elasticsuite-thesaurus/Model/Indexer/IndexHandler.php

Basic implementation for #3713 where leniency is always applied without any check.

[Thesaurus] #3713 Force leniency when creating index
